{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class"]]},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNewTargetingRuleId:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"IAdvizeConversationSDK"}],"title":"initWithNewTargetingRuleId:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithNewTargetingRuleId:"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)NavigationOption(im)initWithNewTargetingRuleId:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class\/initWithNewTargetingRuleId:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/navigationoption-c.class\/initwithnewtargetingruleid:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithNewTargetingRuleId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","kind":"typeIdentifier","text":"TargetingRule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"targetingRule"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-c.class/initWithNewTargetingRuleId:":{"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/navigationoption-c.class\/initwithnewtargetingruleid:","title":"initWithNewTargetingRuleId:","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNewTargetingRuleId:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNewTargetingRuleId:"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class\/initWithNewTargetingRuleId:"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-c.class":{"title":"NavigationOption","abstract":[],"fragments":[{"kind":"identifier","text":"NavigationOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/navigationoption-c.class","type":"topic","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","url":"\/documentation\/iadvizeconversationsdk\/targetingrule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","op":"replace","value":"TargetingRule"},{"op":"replace","value":[{"text":"TargetingRule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TargetingRule"}]}]}]}