{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivationStatus"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationStatus","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"s:22IAdvizeConversationSDK16ActivationStatusO","navigatorTitle":[{"text":"ActivationStatus","kind":"identifier"}],"role":"symbol","title":"ActivationStatus","symbolKind":"enum","roleHeading":"Enumeration"},"seeAlsoSections":[{"anchor":"Activation","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"],"title":"Activation"}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/activationstatus"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/activated","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/activating","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/off"],"generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/Equatable-Implementations","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","doc:\/\/com.iadvize.conversation.sdk\/SE","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH","doc:\/\/com.iadvize.conversation.sdk\/SY"],"title":"Conforms To"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"navigatorTitle":[{"kind":"identifier","text":"ActivationStatus"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationStatus","kind":"identifier"}],"title":"ActivationStatus","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/activationstatus"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus/activated":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/activated","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/activationstatus\/activated","kind":"symbol","abstract":[{"type":"text","text":"The SDK is activated."}],"role":"symbol","title":"ActivationStatus.activated","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"activated","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"kind":"symbol","title":"JWEProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWEProvider"}],"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider","url":"\/documentation\/iadvizeconversationsdk\/jweprovider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWEProvider"}],"abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","title":"GDPROption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/SQ":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SE":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"title":"JWE","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWE"}],"navigatorTitle":[{"text":"JWE","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","url":"\/documentation\/iadvizeconversationsdk\/jwe"},"doc://com.iadvize.conversation.sdk/s8CopyableP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus/off":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"off","kind":"identifier"}],"title":"ActivationStatus.off","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/off","url":"\/documentation\/iadvizeconversationsdk\/activationstatus\/off","abstract":[{"type":"text","text":"The SDK is not initialized. A call to IAdvizeSDK.shared.activate method is needed."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus/activating":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/activating","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/activationstatus\/activating","kind":"symbol","abstract":[{"text":"The SDK is in the process of activation.","type":"text"}],"role":"symbol","title":"ActivationStatus.activating","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activating"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","navigatorTitle":[{"kind":"identifier","text":"GDPRDelegate"}],"title":"GDPRDelegate","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPRDelegate"}],"abstract":[{"text":"An object that is notified about visitor interaction with the GDRP message.","type":"text"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationOption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","title":"AuthenticationOption","type":"topic","abstract":[{"text":"The option to authenticate the visitor.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SY"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/init(rawValue:)","url":"\/documentation\/iadvizeconversationsdk\/activationstatus\/init(rawvalue:)","abstract":[],"type":"topic","title":"init(rawValue:)","role":"symbol","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus/Equatable-Implementations":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/Equatable-Implementations","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/activationstatus\/equatable-implementations","kind":"article","abstract":[],"role":"collectionGroup","title":"Equatable Implementations"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GDPREnabledOption","kind":"identifier"}],"navigatorTitle":[{"text":"GDPREnabledOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","title":"GDPREnabledOption","kind":"symbol","abstract":[{"text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus\/RawRepresentable-Implementations","url":"\/documentation\/iadvizeconversationsdk\/activationstatus\/rawrepresentable-implementations","abstract":[],"type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article"}},"variantOverrides":[{"patch":[{"value":"JWE","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments","op":"replace","value":[{"text":"JWE","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"JWE"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title","op":"replace","value":"GDPRDelegate"},{"op":"replace","value":[{"text":"GDPRDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}