{
  "abstract" : [
    {
      "text" : "Mode for APNS.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:22IAdvizeConversationSDK15ApplicationModeO",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "enum"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "ApplicationMode"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "ApplicationMode"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Enumeration",
    "symbolKind" : "enum",
    "title" : "ApplicationMode"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "enum"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "ApplicationMode"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/SQ",
        "doc:\/\/com.iadvize.conversation.sdk\/SH",
        "doc:\/\/com.iadvize.conversation.sdk\/SY"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "seeAlsoSections" : [
    {
      "anchor" : "Push-Notifications",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController"
      ],
      "title" : "Push Notifications"
    }
  ],
  "topicSections" : [
    {
      "anchor" : "Enumeration-Cases",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/dev",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/prod"
      ],
      "title" : "Enumeration Cases"
    },
    {
      "anchor" : "Initializers",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/init(rawValue:)"
      ],
      "title" : "Initializers"
    },
    {
      "anchor" : "Default-Implementations",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/Equatable-Implementations",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/RawRepresentable-Implementations"
      ],
      "title" : "Default Implementations"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/applicationmode"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/SH": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/SQ": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/SY": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/SY",
  "title" : "Swift.RawRepresentable",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode": {
  "abstract" : [
    {
      "text" : "Mode for APNS.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ApplicationMode"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ApplicationMode"
    }
  ],
  "role" : "symbol",
  "title" : "ApplicationMode",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/applicationmode"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode/Equatable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/Equatable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "Equatable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/applicationmode\/equatable-implementations"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode/RawRepresentable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/RawRepresentable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "RawRepresentable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/applicationmode\/rawrepresentable-implementations"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode/dev": {
  "abstract" : [
    {
      "text" : "For Sandbox environment.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "dev"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/dev",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "ApplicationMode.dev",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/applicationmode\/dev"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode/init(rawValue:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "?("
    },
    {
      "kind" : "externalParam",
      "text" : "rawValue"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/init(rawValue:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(rawValue:)",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/applicationmode\/init(rawvalue:)"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode/prod": {
  "abstract" : [
    {
      "text" : "For Production environment.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "prod"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode\/prod",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "ApplicationMode.prod",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/applicationmode\/prod"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController": {
  "abstract" : [
    {
      "text" : "An object that allows to configure push notifications.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "NotificationController"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "NotificationController"
    }
  ],
  "role" : "symbol",
  "title" : "NotificationController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/notificationcontroller"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/title",
        "value" : "NotificationController"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "NotificationController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "NotificationController"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}