{
  "abstract" : [
    {
      "text" : "Encapsulate all the configuration options that can be applied to the chatbox.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:22IAdvizeConversationSDK20ChatboxConfigurationV",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "struct"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "ChatboxConfiguration"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "ChatboxConfiguration"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Structure",
    "symbolKind" : "struct",
    "title" : "ChatboxConfiguration"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "struct"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "ChatboxConfiguration"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "overview",
          "level" : 2,
          "text" : "Overview",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Usage: instantiate a default configuration, set the properties you want, and apply them to the chatbox:",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        },
        {
          "code" : [
            "var configuration = ChatboxConfiguration()",
            "configuration.primaryColor = .red",
            "IAdvizeSDK.shared.chatboxController.setupChatbox(configuration: configuration)"
          ],
          "syntax" : null,
          "type" : "codeListing"
        }
      ],
      "kind" : "content"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/s8SendableP",
        "doc:\/\/com.iadvize.conversation.sdk\/s16SendableMetatypeP"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "seeAlsoSections" : [
    {
      "anchor" : "Chatbox-and-Chat-button",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate"
      ],
      "title" : "Chatbox and Chat button"
    }
  ],
  "topicSections" : [
    {
      "anchor" : "Initializers",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/init()"
      ],
      "title" : "Initializers"
    },
    {
      "anchor" : "Instance-Properties",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/automaticMessage",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/avatar",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/font",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/gdprMessage",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/isSmallerChatboxEnabled",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/presentationStyle",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/presentingViewController",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/primaryColor",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/primaryTextColor",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/secondaryColor",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/secondaryTextColor",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/title"
      ],
      "title" : "Instance Properties"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration": {
  "abstract" : [
    {
      "text" : "Encapsulate all the configuration options that can be applied to the chatbox.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ChatboxConfiguration"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ChatboxConfiguration"
    }
  ],
  "role" : "symbol",
  "title" : "ChatboxConfiguration",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/automaticMessage": {
  "abstract" : [
    {
      "text" : "Content of the first automatic message that invites your visitor to start asking a question.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "automaticMessage"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/automaticMessage",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "automaticMessage",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/automaticmessage"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/avatar": {
  "abstract" : [
    {
      "text" : "Avatar displayed in the Chatbox header (above the ",
      "type" : "text"
    },
    {
      "code" : "title",
      "type" : "codeVoice"
    },
    {
      "text" : ").",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "avatar"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIImage",
      "text" : "UIImage"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/avatar",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "avatar",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/avatar"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/font": {
  "abstract" : [
    {
      "text" : "Font that will be used to display text in all UI elements of the iAdvize SDK.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "font"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIFont",
      "text" : "UIFont"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/font",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "font",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/font"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/gdprMessage": {
  "abstract" : [
    {
      "text" : "Content of the first GDPR message which invites your visitor to accept or decline the GDPR consent.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "gdprMessage"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/gdprMessage",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "gdprMessage",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/gdprmessage"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/init()": {
  "abstract" : [
    {
      "text" : "Create a ",
      "type" : "text"
    },
    {
      "code" : "ChatboxConfiguration",
      "type" : "codeVoice"
    },
    {
      "text" : " with the default values.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/init()",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init()",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/init()"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/isSmallerChatboxEnabled": {
  "abstract" : [
    {
      "text" : "When enabled, the Chatbox will appear in compact mode.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "isSmallerChatboxEnabled"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/isSmallerChatboxEnabled",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "isSmallerChatboxEnabled",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/issmallerchatboxenabled"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/presentationStyle": {
  "abstract" : [
    {
      "text" : "Presentation style of the Chatbox.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "presentationStyle"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@UIModalPresentationStyle",
      "text" : "UIModalPresentationStyle"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/presentationStyle",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "presentationStyle",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/presentationstyle"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/presentingViewController": {
  "abstract" : [
    {
      "text" : "If specified, this view controller will be used to present the chatbox, when the default chat button",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "is tapped.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "presentingViewController"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIViewController",
      "text" : "UIViewController"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/presentingViewController",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "presentingViewController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/presentingviewcontroller"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/primaryColor": {
  "abstract" : [
    {
      "text" : "Primary color used in the Chatbox.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "primaryColor"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIColor",
      "text" : "UIColor"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/primaryColor",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "primaryColor",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/primarycolor"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/primaryTextColor": {
  "abstract" : [
    {
      "text" : "Primary text color used in the Chatbox.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "primaryTextColor"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIColor",
      "text" : "UIColor"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/primaryTextColor",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "primaryTextColor",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/primarytextcolor"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/secondaryColor": {
  "abstract" : [
    {
      "text" : "Secondary color used in the Chatbox.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "secondaryColor"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIColor",
      "text" : "UIColor"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/secondaryColor",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "secondaryColor",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/secondarycolor"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/secondaryTextColor": {
  "abstract" : [
    {
      "text" : "Secondary text color used in the Chatbox.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "secondaryTextColor"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:objc(cs)UIColor",
      "text" : "UIColor"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/secondaryTextColor",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "secondaryTextColor",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/secondarytextcolor"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration/title": {
  "abstract" : [
    {
      "text" : "Title displayed in the Chatbox header (below the ",
      "type" : "text"
    },
    {
      "code" : "avatar",
      "type" : "codeVoice"
    },
    {
      "text" : ").",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "title"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SS",
      "text" : "String"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration\/title",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "title",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxconfiguration\/title"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController": {
  "abstract" : [
    {
      "text" : "An object that controls the chatbox, which is where the conversation is displayed, and the chat button.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ChatboxController"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ChatboxController"
    }
  ],
  "role" : "symbol",
  "title" : "ChatboxController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxcontroller"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxControllerDelegate": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ChatboxControllerDelegate"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ChatboxControllerDelegate"
    }
  ],
  "role" : "symbol",
  "title" : "ChatboxControllerDelegate",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxcontrollerdelegate"
},
"doc://com.iadvize.conversation.sdk/s16SendableMetatypeP": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/s16SendableMetatypeP",
  "title" : "Swift.SendableMetatype",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/s8SendableP": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/s8SendableP",
  "title" : "Swift.Sendable",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title",
        "value" : "ChatboxController"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ChatboxController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ChatboxController"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}