{"kind":"symbol","metadata":{"symbolKind":"struct","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"s:22IAdvizeConversationSDK20ChatboxConfigurationV","roleHeading":"Structure","title":"ChatboxConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatboxConfiguration"}],"navigatorTitle":[{"text":"ChatboxConfiguration","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/init()"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/accentColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/automaticMessage","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/font","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/gdprMessage","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageAvatar","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageBackgroundColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageBorderColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageTextColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/mainColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/navigationBarBackgroundColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/navigationBarMainColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/navigationBarTitle","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/outgoingMessageBackgroundColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/outgoingMessageBorderColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/outgoingMessageTextColor","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/presentationStyle","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/presentingViewController"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ChatboxConfiguration","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Usage: instantiate a default configuration, set the properties you want, and apply them to the chatbox:"}],"type":"paragraph"},{"code":["var configuration = ChatboxConfiguration()","configuration.accentColor = .red","IAdvizeSDK.shared.chatboxController.setupChatbox(configuration: configuration)"],"syntax":null,"type":"codeListing"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Encapsulate all the configuration options that can be applied to the chatbox.","type":"text"}],"seeAlsoSections":[{"anchor":"Chatbox-and-Chat-button","title":"Chatbox and Chat button","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/incomingMessageBorderColor":{"title":"incomingMessageBorderColor","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageBorderColor","abstract":[{"type":"text","text":"Color of message border for incoming (operator) messages"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"incomingMessageBorderColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/incomingmessagebordercolor","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/presentationStyle":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","kind":"typeIdentifier","text":"UIModalPresentationStyle"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Presentation style of the Chatbox."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/presentationStyle","title":"presentationStyle","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/presentationstyle","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/outgoingMessageBorderColor":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/outgoingMessageBorderColor","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/outgoingmessagebordercolor","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"outgoingMessageBorderColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"outgoingMessageBorderColor","abstract":[{"type":"text","text":"Color of message border for outgoing (visitor) messages"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/outgoingMessageBackgroundColor":{"title":"outgoingMessageBackgroundColor","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"outgoingMessageBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"abstract":[{"text":"Color of message bubble for outgoing (visitor) messages","type":"text"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/outgoingMessageBackgroundColor","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/outgoingmessagebackgroundcolor"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/navigationBarTitle":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/navigationBarTitle","abstract":[{"type":"text","text":"Localized title of the Conversation Navigation Bar."}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/navigationbartitle","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationBarTitle","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","title":"navigationBarTitle"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IncomingMessageAvatar-swift.enum":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum","kind":"symbol","abstract":[{"text":"The image used for the incoming message avatar.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-swift.enum","type":"topic","title":"IncomingMessageAvatar","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IncomingMessageAvatar"}],"role":"symbol","navigatorTitle":[{"text":"IncomingMessageAvatar","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/font":{"abstract":[{"text":"Font that will be used to display text in all UI elements of the iAdvize SDK.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/font","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/font","role":"symbol","title":"font","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"font","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?","kind":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/accentColor":{"title":"accentColor","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/accentColor","abstract":[{"type":"text","text":"Color used for message controls (quick answers, file messages, send button etc…)"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"accentColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/accentcolor","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatboxController"}],"title":"ChatboxController","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","abstract":[{"text":"An object that controls the chatbox, which is where the conversation is displayed, and the chat button.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatboxController","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct","navigatorTitle":[{"kind":"identifier","text":"ChatboxConfiguration"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatboxConfiguration"}],"role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct","title":"ChatboxConfiguration","abstract":[{"type":"text","text":"Encapsulate all the configuration options that can be applied to the chatbox."}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/presentingViewController":{"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/presentingviewcontroller","type":"topic","kind":"symbol","title":"presentingViewController","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"presentingViewController","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?"}],"abstract":[{"text":"If specified, this view controller will be used to present the chatbox, when the default chat button","type":"text"},{"text":" ","type":"text"},{"text":"is tapped.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/presentingViewController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxControllerDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate","title":"ChatboxControllerDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ChatboxControllerDelegate","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontrollerdelegate","navigatorTitle":[{"text":"ChatboxControllerDelegate","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/automaticMessage":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/automaticMessage","abstract":[{"type":"text","text":"Content of the first automatic message that invites your visitor to start asking a question."}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/automaticmessage","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"automaticMessage","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","title":"automaticMessage"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/incomingMessageBackgroundColor":{"abstract":[{"type":"text","text":"Color of message bubble for incoming (operator) messages"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"incomingMessageBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"title":"incomingMessageBackgroundColor","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/incomingmessagebackgroundcolor","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageBackgroundColor"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/incomingMessageAvatar":{"title":"incomingMessageAvatar","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageAvatar","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/incomingmessageavatar","kind":"symbol","abstract":[{"text":"Incoming message (chat operator message) avatar.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incomingMessageAvatar"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IncomingMessageAvatar","preciseIdentifier":"s:22IAdvizeConversationSDK21IncomingMessageAvatarO"},{"text":"?","kind":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/navigationBarBackgroundColor":{"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/navigationbarbackgroundcolor","title":"navigationBarBackgroundColor","role":"symbol","abstract":[{"type":"text","text":"Background color of the Navigation Bar of the chatbox."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationBarBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/navigationBarBackgroundColor","type":"topic","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/outgoingMessageTextColor":{"kind":"symbol","type":"topic","title":"outgoingMessageTextColor","abstract":[{"type":"text","text":"Color of message text for outgoing (visitor) messages"}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/outgoingmessagetextcolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"outgoingMessageTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/outgoingMessageTextColor"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/navigationBarMainColor":{"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/navigationbarmaincolor","title":"navigationBarMainColor","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"navigationBarMainColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/navigationBarMainColor","abstract":[{"text":"Color of the elements which are contained in the Navigation Bar.","type":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/init()":{"title":"init()","abstract":[{"text":"Create a ","type":"text"},{"type":"codeVoice","code":"ChatboxConfiguration"},{"type":"text","text":" with the default values."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/init()","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/init()","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/gdprMessage":{"abstract":[{"text":"Content of the first GDPR message which invites your visitor to accept or decline the GDPR consent.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gdprMessage","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/gdprmessage","type":"topic","title":"gdprMessage","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/gdprMessage","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/mainColor":{"kind":"symbol","role":"symbol","title":"mainColor","deprecated":true,"type":"topic","abstract":[{"type":"text","text":"Main color of the chatbox and chat button."}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/maincolor","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/mainColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mainColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct/incomingMessageTextColor":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct\/incomingMessageTextColor","abstract":[{"text":"Color of message text for incoming (operator) messages","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct\/incomingmessagetextcolor","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incomingMessageTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"incomingMessageTextColor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ChatboxController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments","value":[{"text":"ChatboxController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatboxController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/title","op":"replace","value":"ChatboxControllerDelegate"},{"value":[{"text":"ChatboxControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"ChatboxControllerDelegate","kind":"identifier"}]}]}]}