{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GDPREnabledOption"}],"externalID":"s:22IAdvizeConversationSDK17GDPREnabledOptionO","modules":[{"name":"IAdvizeConversationSDK"}],"title":"GDPREnabledOption","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPREnabledOption"}],"symbolKind":"enum"},"sections":[],"seeAlsoSections":[{"title":"Activation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"],"generated":true,"anchor":"Activation"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum\/delegate(delegate:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum\/legalInformation(url:)"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPREnabledOption"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"title":"JWE","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWE"}],"navigatorTitle":[{"text":"JWE","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","url":"\/documentation\/iadvizeconversationsdk\/jwe"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","title":"GDPROption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum/delegate(delegate:)":{"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum\/delegate(delegate:)","type":"topic","abstract":[{"type":"text","text":"Notify the specified delegate."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum\/delegate(delegate:)","title":"GDPREnabledOption.delegate(delegate:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GDPRDelegate","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(pl)GDPRDelegate"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"navigatorTitle":[{"kind":"identifier","text":"ActivationStatus"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationStatus","kind":"identifier"}],"title":"ActivationStatus","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/activationstatus"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationOption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","title":"AuthenticationOption","type":"topic","abstract":[{"text":"The option to authenticate the visitor.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"kind":"symbol","title":"JWEProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWEProvider"}],"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider","url":"\/documentation\/iadvizeconversationsdk\/jweprovider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWEProvider"}],"abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum/legalInformation(url:)":{"title":"GDPREnabledOption.legalInformation(url:)","type":"topic","abstract":[{"type":"text","text":"Let the iAdvize SDK open the specified URL."}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum\/legalinformation(url:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum\/legalInformation(url:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"legalInformation"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GDPREnabledOption","kind":"identifier"}],"navigatorTitle":[{"text":"GDPREnabledOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","title":"GDPREnabledOption","kind":"symbol","abstract":[{"text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","navigatorTitle":[{"kind":"identifier","text":"GDPRDelegate"}],"title":"GDPRDelegate","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPRDelegate"}],"abstract":[{"text":"An object that is notified about visitor interaction with the GDRP message.","type":"text"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"value":"JWE","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JWE"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments"},{"value":[{"text":"JWE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title","value":"GDPRDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"GDPRDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle","op":"replace","value":[{"text":"GDPRDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}