{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JWE","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JWE"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)JWE","modules":[{"name":"IAdvizeConversationSDK"}],"title":"JWE","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JWE","kind":"identifier"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"Activation","title":"Activation","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/jwe"]},{"paths":["\/documentation\/iadvizeconversationsdk\/jwe"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE\/init(value:)"],"title":"Initializers","generated":true,"anchor":"Initializers"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"kind":"symbol","references":{"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","title":"GDPROption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"title":"JWE","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWE"}],"navigatorTitle":[{"text":"JWE","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","url":"\/documentation\/iadvizeconversationsdk\/jwe"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"navigatorTitle":[{"kind":"identifier","text":"ActivationStatus"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationStatus","kind":"identifier"}],"title":"ActivationStatus","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/activationstatus"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","navigatorTitle":[{"kind":"identifier","text":"GDPRDelegate"}],"title":"GDPRDelegate","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPRDelegate"}],"abstract":[{"text":"An object that is notified about visitor interaction with the GDRP message.","type":"text"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"GDPREnabledOption","kind":"identifier"}],"navigatorTitle":[{"text":"GDPREnabledOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","title":"GDPREnabledOption","kind":"symbol","abstract":[{"text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE/init(value:)":{"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/jwe\/init(value:)","type":"topic","abstract":[],"title":"init(value:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE\/init(value:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationOption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","title":"AuthenticationOption","type":"topic","abstract":[{"text":"The option to authenticate the visitor.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"kind":"symbol","title":"JWEProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWEProvider"}],"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider","url":"\/documentation\/iadvizeconversationsdk\/jweprovider","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWEProvider"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"JWE","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JWE"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JWE","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"replace"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"Activation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate"],"title":"Activation","generated":true}]},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWE","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"JWE","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title"},{"value":[{"text":"JWE","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"JWE"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title","value":"GDPRDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"GDPRDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}]}]}]}