{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation\/conversationChannel","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation\/conversationId"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OngoingConversation","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/ongoingconversation"]},{"paths":["\/documentation\/iadvizeconversationsdk\/ongoingconversation"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)OngoingConversation","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OngoingConversation"}],"navigatorTitle":[{"text":"OngoingConversation","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"title":"OngoingConversation","symbolKind":"class","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SE","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"],"title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"],"title":"Conversation","generated":true,"anchor":"Conversation"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.iadvize.conversation.sdk/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","type":"topic","role":"symbol","title":"ConversationController","navigatorTitle":[{"text":"ConversationController","kind":"identifier"}],"abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationController","kind":"identifier"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationControllerDelegate"}],"abstract":[{"text":"An object that is notified about the ongoing conversation.","type":"text"}],"title":"ConversationControllerDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConversationControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"},"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SE","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation/conversationChannel":{"title":"conversationChannel","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation\/conversationChannel","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation\/conversationchannel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationChannel"},{"kind":"text","text":": "},{"text":"ConversationChannel","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO","kind":"typeIdentifier"}],"abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation/conversationId":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation\/conversationid","title":"conversationId","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation\/conversationId","type":"topic","role":"symbol"},"doc://com.iadvize.conversation.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation":{"role":"symbol","title":"OngoingConversation","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OngoingConversation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"OngoingConversation","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"OngoingConversation","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OngoingConversation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OngoingConversation"}]},{"value":null,"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"]}]},{"value":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"],"title":"Conversation","generated":true,"anchor":"Conversation"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"OngoingConversation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title","value":"ConversationController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments","value":[{"text":"ConversationController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ConversationController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle","op":"replace"},{"value":"ConversationControllerDelegate","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/fragments","op":"replace","value":[{"text":"ConversationControllerDelegate","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/navigatorTitle"},{"value":"OngoingConversation","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/title"},{"value":[{"kind":"identifier","text":"OngoingConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/fragments"},{"value":[{"kind":"identifier","text":"OngoingConversation"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/navigatorTitle"}]}]}