{
  "abstract" : [
    {
      "text" : "An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@IAdvizeConversationSDK@objc(cs)TargetingController",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "class"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TargetingController"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TargetingController"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Class",
    "symbolKind" : "class",
    "title" : "TargetingController"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "final"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "class"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TargetingController"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"
      ],
      "kind" : "relationships",
      "title" : "Inherits From",
      "type" : "inheritsFrom"
    },
    {
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject",
        "doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP",
        "doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP",
        "doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP",
        "doc:\/\/com.iadvize.conversation.sdk\/SQ",
        "doc:\/\/com.iadvize.conversation.sdk\/SH"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "seeAlsoSections" : [
    {
      "anchor" : "Targeting",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language"
      ],
      "title" : "Targeting"
    }
  ],
  "topicSections" : [
    {
      "anchor" : "Instance-Properties",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/delegate",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/isActiveTargetingRuleAvailable",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/language"
      ],
      "title" : "Instance Properties"
    },
    {
      "anchor" : "Instance-Methods",
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/activateTargetingRule(targetingRule:)",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/deactivateTargetingRule()"
      ],
      "title" : "Instance Methods"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/targetingcontroller"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/targetingcontroller"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/SH": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/SH",
  "title" : "Swift.Hashable",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/SQ": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language": {
  "abstract" : [
    {
      "text" : "ISO639-1 language.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Language"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Language"
    }
  ],
  "role" : "symbol",
  "title" : "Language",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/language"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption": {
  "abstract" : [
    {
      "text" : "Option to specify the language to use for the targeting.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "SDKLanguageOption"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "SDKLanguageOption"
    }
  ],
  "role" : "symbol",
  "title" : "SDKLanguageOption",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/sdklanguageoption"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController": {
  "abstract" : [
    {
      "text" : "An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TargetingController"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TargetingController"
    }
  ],
  "role" : "symbol",
  "title" : "TargetingController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/activateTargetingRule(targetingRule:)": {
  "abstract" : [
    {
      "text" : "Activate the specified targeting rule.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "activateTargetingRule"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "targetingRule"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule",
      "text" : "TargetingRule"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/activateTargetingRule(targetingRule:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "activateTargetingRule(targetingRule:)",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller\/activatetargetingrule(targetingrule:)"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/deactivateTargetingRule()": {
  "abstract" : [
    {
      "text" : "Deactivate the current targeting rule.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "deactivateTargetingRule"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/deactivateTargetingRule()",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "deactivateTargetingRule()",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller\/deactivatetargetingrule()"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/delegate": {
  "abstract" : [
    {
      "text" : "The object notified about the targeting process.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "delegate"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:22IAdvizeConversationSDK27TargetingControllerDelegateP",
      "text" : "TargetingControllerDelegate"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/delegate",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "delegate",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller\/delegate"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/init": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "text",
      "text" : "- "
    },
    {
      "kind" : "identifier",
      "text" : "init"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/init",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "init"
    }
  ],
  "role" : "symbol",
  "title" : "init",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller\/init"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/isActiveTargetingRuleAvailable": {
  "abstract" : [
    {
      "text" : "Indicates if the targeting rule that was activated is available, meaning that a respondent associated to the",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "rule is available to answer.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "isActiveTargetingRuleAvailable"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/isActiveTargetingRuleAvailable",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "isActiveTargetingRuleAvailable",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller\/isactivetargetingruleavailable"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/language": {
  "abstract" : [
    {
      "text" : "The option used to configure the language of the conversation.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "language"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:22IAdvizeConversationSDK17SDKLanguageOptionO",
      "text" : "SDKLanguageOption"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/language",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "language",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller\/language"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate": {
  "abstract" : [
    {
      "text" : "An object that is notified about the targeting process.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TargetingControllerDelegate"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TargetingControllerDelegate"
    }
  ],
  "role" : "symbol",
  "title" : "TargetingControllerDelegate",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError": {
  "abstract" : [
    {
      "code" : "TargetingError",
      "type" : "codeVoice"
    },
    {
      "text" : " is an error that can occur when you try to activate a targeting rule using",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "code" : "TargetingController.activateTargetingRule(targetingRule:)",
      "type" : "codeVoice"
    },
    {
      "text" : ".",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TargetingError"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TargetingError"
    }
  ],
  "role" : "symbol",
  "title" : "TargetingError",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingerror"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TargetingRule"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TargetingRule"
    }
  ],
  "role" : "symbol",
  "title" : "TargetingRule",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingrule"
},
"doc://com.iadvize.conversation.sdk/objc(cs)NSObject": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject",
  "title" : "NSObject",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/objc(pl)NSObject": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject",
  "title" : "ObjectiveC.NSObjectProtocol",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP",
  "title" : "Swift.CustomStringConvertible",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP",
  "title" : "Swift.CustomDebugStringConvertible",
  "type" : "unresolvable"
},
"doc://com.iadvize.conversation.sdk/s7CVarArgP": {
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP",
  "title" : "Swift.CVarArg",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "add",
        "path" : "\/metadata\/platforms",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TargetingController"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "class"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "anchor" : "Instance-Methods",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/init"
            ],
            "title" : "Instance Methods"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : [
          {
            "identifiers" : [
              "doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"
            ],
            "kind" : "relationships",
            "title" : "Inherits From",
            "type" : "inheritsFrom"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/seeAlsoSections",
        "value" : [
          {
            "anchor" : "Targeting",
            "generated" : true,
            "identifiers" : [
              "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule"
            ],
            "title" : "Targeting"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@interface"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "TargetingController"
                },
                {
                  "kind" : "text",
                  "text" : " : "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:objc(cs)NSObject",
                  "text" : "NSObject"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title",
        "value" : "TargetingController"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title",
        "value" : "TargetingRule"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingRule"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingRule"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}