{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSCoding","doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"Transactions","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency"],"anchor":"Transactions"}],"abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/transaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/transaction"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Transaction"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"Transaction","navigatorTitle":[{"text":"Transaction","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Transaction","kind":"identifier"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)Transaction","symbolKind":"class","roleHeading":"Class","modules":[{"name":"IAdvizeConversationSDK"}],"role":"symbol"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/init(coder:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/init(externalTransactionId:date:amount:currency:)"],"title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/amount","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/currency","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/date","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/externalTransactionId"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/encode(with:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/init(externalTransactionId:date:amount:currency:)":{"url":"\/documentation\/iadvizeconversationsdk\/transaction\/init(externaltransactionid:date:amount:currency:)","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/init(externalTransactionId:date:amount:currency:)","title":"init(externalTransactionId:date:amount:currency:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"externalTransactionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"date","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"amount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22IAdvizeConversationSDK8CurrencyO","text":"Currency","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Create a new transaction.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/amount":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amount"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/transaction\/amount","abstract":[{"text":"The amount of the transaction.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/amount","role":"symbol","title":"amount"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Currency":{"abstract":[{"text":"Currency used in a ","type":"text"},{"type":"codeVoice","code":"Transaction"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"Currency","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency","title":"Currency","url":"\/documentation\/iadvizeconversationsdk\/currency","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Currency"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/transaction\/isequal(_:)","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/isEqual(_:)","role":"symbol","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TransactionController","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller","title":"TransactionController","type":"topic","role":"symbol","navigatorTitle":[{"text":"TransactionController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/externalTransactionId":{"url":"\/documentation\/iadvizeconversationsdk\/transaction\/externaltransactionid","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/externalTransactionId","title":"externalTransactionId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalTransactionId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A unique identifier for the transaction."}],"kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP"},"doc://com.iadvize.conversation.sdk/objc(pl)NSCoding":{"title":"NSCoding","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSCoding"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/initWithExternalTransactionId:date:amount:currency:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithExternalTransactionId:date:amount:currency:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/transaction\/initwithexternaltransactionid:date:amount:currency:","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/initWithExternalTransactionId:date:amount:currency:","abstract":[],"role":"symbol","title":"initWithExternalTransactionId:date:amount:currency:","navigatorTitle":[{"text":"initWithExternalTransactionId:date:amount:currency:","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/init(coder:)":{"url":"\/documentation\/iadvizeconversationsdk\/transaction\/init(coder:)","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"title":"init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"title":"Transaction","navigatorTitle":[{"text":"Transaction","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","type":"topic","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Transaction"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/date":{"title":"date","abstract":[{"text":"The date of the transaction.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/transaction\/date","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/date","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"date"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}]},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/encode(with:)":{"kind":"symbol","title":"encode(with:)","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/encode(with:)","url":"\/documentation\/iadvizeconversationsdk\/transaction\/encode(with:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/currency":{"kind":"symbol","title":"currency","abstract":[{"type":"text","text":"The currency of the transaction."}],"url":"\/documentation\/iadvizeconversationsdk\/transaction\/currency","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/currency","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"kind":"text","text":": "},{"text":"Currency","preciseIdentifier":"s:22IAdvizeConversationSDK8CurrencyO","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/SQ":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"Transaction","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Transaction"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Transaction","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/encode(with:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/init(coder:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/initWithExternalTransactionId:date:amount:currency:","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSCoding"],"type":"conformsTo"}]},{"op":"replace","value":[{"title":"Transactions","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController"],"generated":true,"anchor":"Transactions"}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Transaction"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/title","value":"TransactionController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/fragments","value":[{"text":"TransactionController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TransactionController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/navigatorTitle","op":"replace"},{"value":"initWithCoder:","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction~1init(coder:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction~1init(coder:)\/fragments","op":"replace"},{"op":"replace","value":"Transaction","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments","value":[{"kind":"identifier","text":"Transaction"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle","value":[{"text":"Transaction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction~1encode(with:)\/title","value":"encodeWithCoder:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encodeWithCoder:"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction~1encode(with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}