platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'IAdvizeSwiftExample' do
    project 'IAdvizeSwiftExample'

    pod 'iAdvize', :path => '../../../mobile-ios-sdk-conversation-library'
end
