{"abstract":[{"text":"Activate the specified targeting rule.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontroller\/activatetargetingrule(targetingrule:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontroller\/activatetargetingrule(targetingrule:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"activateTargetingRule","kind":"identifier"},{"kind":"text","text":"("},{"text":"targetingRule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TargetingRule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"targetingRule","content":[{"inlineContent":[{"type":"text","text":"The targeting rule to activate."}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"When you activate a targeting rule, it allows the iAdvize SDK to target the visitor. If one of the respondents","type":"text"},{"type":"text","text":" "},{"text":"associated with the targeting rule is available, the chat button will be displayed so the visitor can start a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"conversation."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"You can retrieve your targeting rule IDs in the “Engagement” section in the iAdvize administration.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController"]]},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/activateTargetingRule(targetingRule:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"title":"activateTargetingRule(targetingRule:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activateTargetingRule"},{"text":"(","kind":"text"},{"text":"targetingRule","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TargetingRule","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule"},{"text":")","kind":"text"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingController(im)activateTargetingRuleWithTargetingRule:","navigatorTitle":[{"text":"activateTargetingRuleWithTargetingRule:","kind":"identifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingrule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","title":"TargetingRule","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TargetingRule","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/activateTargetingRule(targetingRule:)":{"navigatorTitle":[{"text":"activateTargetingRuleWithTargetingRule:","kind":"identifier"}],"title":"activateTargetingRule(targetingRule:)","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller\/activatetargetingrule(targetingrule:)","kind":"symbol","abstract":[{"text":"Activate the specified targeting rule.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/activateTargetingRule(targetingRule:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activateTargetingRule","kind":"identifier"},{"kind":"text","text":"("},{"text":"targetingRule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TargetingRule","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TargetingController","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"title":"TargetingController","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"activateTargetingRuleWithTargetingRule:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"activateTargetingRuleWithTargetingRule:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"activateTargetingRuleWithTargetingRule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","text":"TargetingRule"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"targetingRule"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The targeting rule to activate.","type":"text"}],"type":"paragraph"}],"name":"targetingRule"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","value":"TargetingRule"},{"value":[{"text":"TargetingRule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments"},{"value":[{"text":"TargetingRule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle"},{"value":"activateTargetingRuleWithTargetingRule:","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController~1activateTargetingRule(targetingRule:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController~1activateTargetingRule(targetingRule:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"activateTargetingRuleWithTargetingRule:","kind":"identifier"}]},{"op":"replace","value":"TargetingController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","value":[{"text":"TargetingController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TargetingController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}