{"metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"roleHeading":"Instance Method","title":"getLanguage","externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)TargetingController(im)getLanguage","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getLanguage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getLanguage"}]},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/getLanguage"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontroller\/getlanguage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"SDKLanguageOption","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-c.class","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)SDKLanguageOption"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getLanguage"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/getLanguage":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/getLanguage","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller\/getlanguage","title":"getLanguage","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getLanguage"}],"navigatorTitle":[{"kind":"identifier","text":"getLanguage"}],"abstract":[],"type":"topic","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-c.class":{"title":"SDKLanguageOption","abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-c.class","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-c.class","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"SDKLanguageOption"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TargetingController","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"title":"TargetingController","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title","op":"replace","value":"TargetingController"},{"value":[{"kind":"identifier","text":"TargetingController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments"},{"value":[{"text":"TargetingController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}