{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerUserNavigationWithNavigationOption:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NavigationOption","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)NavigationOption","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class"},{"text":" *) ","kind":"text"},{"text":"navigationOption","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/registerUserNavigationWithNavigationOption:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"registerUserNavigationWithNavigationOption:","fragments":[{"text":"- ","kind":"text"},{"text":"registerUserNavigationWithNavigationOption:","kind":"identifier"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerUserNavigationWithNavigationOption:"}],"modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)TargetingController(im)registerUserNavigationWithNavigationOption:","roleHeading":"Instance Method"},"kind":"symbol","variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontroller\/registerusernavigationwithnavigationoption:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/registerUserNavigationWithNavigationOption:":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/registerUserNavigationWithNavigationOption:","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller\/registerusernavigationwithnavigationoption:","title":"registerUserNavigationWithNavigationOption:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerUserNavigationWithNavigationOption:"}],"navigatorTitle":[{"kind":"identifier","text":"registerUserNavigationWithNavigationOption:"}],"abstract":[],"type":"topic","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TargetingController","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"title":"TargetingController","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-c.class":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class","title":"NavigationOption","kind":"symbol","role":"symbol","fragments":[{"text":"NavigationOption","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-c.class","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TargetingController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","op":"replace","value":[{"text":"TargetingController","kind":"identifier"}]},{"value":[{"text":"TargetingController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","op":"replace"}]}]}