{
  "abstract" : [
    {
      "text" : "The object notified of events related to the conversation such as new messages received.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController\/delegate"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@IAdvizeConversationSDK@objc(cs)ChatboxController(py)delegate",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "var"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "delegate"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(pl)ChatboxControllerDelegate",
        "text" : "ChatboxControllerDelegate"
      },
      {
        "kind" : "text",
        "text" : "?"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "delegate"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Property",
    "symbolKind" : "property",
    "title" : "delegate"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "attribute",
              "text" : "@objc"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "weak"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "var"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "delegate"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(pl)ChatboxControllerDelegate",
              "text" : "ChatboxControllerDelegate"
            },
            {
              "kind" : "text",
              "text" : "?"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/delegate"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/delegate"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController": {
  "abstract" : [
    {
      "text" : "An object that controls the chatbox, which is where the conversation is displayed, and the chat button.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ChatboxController"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ChatboxController"
    }
  ],
  "role" : "symbol",
  "title" : "ChatboxController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxcontroller"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController/delegate": {
  "abstract" : [
    {
      "text" : "The object notified of events related to the conversation such as new messages received.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "delegate"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(pl)ChatboxControllerDelegate",
      "text" : "ChatboxControllerDelegate"
    },
    {
      "kind" : "text",
      "text" : "?"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController\/delegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "delegate"
    }
  ],
  "role" : "symbol",
  "title" : "delegate",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/delegate"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxControllerDelegate": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "ChatboxControllerDelegate"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "ChatboxControllerDelegate"
    }
  ],
  "role" : "symbol",
  "title" : "ChatboxControllerDelegate",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/chatboxcontrollerdelegate"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "delegate"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "delegate"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@property"
                },
                {
                  "kind" : "text",
                  "text" : " ("
                },
                {
                  "kind" : "keyword",
                  "text" : "nonatomic"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "weak"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:Qo@M@IAdvizeConversationSDK@objc(pl)ChatboxControllerDelegate",
                  "text" : "id<ChatboxControllerDelegate>"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "delegate"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title",
        "value" : "ChatboxController"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ChatboxController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ChatboxController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController~1delegate\/title",
        "value" : "delegate"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController~1delegate\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "delegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/title",
        "value" : "ChatboxControllerDelegate"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ChatboxControllerDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "ChatboxControllerDelegate"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}