{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useDefaultFloatingButton"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"When the active targeting rule is available, a chat button is displayed to invite the user to chat.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"To let the SDK manage and display its default chat button, set this value to "},{"code":"true","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"To use a custom chat button instead, set this value to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"The default value is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"useDefaultFloatingButton","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"useDefaultFloatingButton","kind":"identifier"}],"symbolKind":"property","title":"useDefaultFloatingButton","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)ChatboxController(py)useDefaultFloatingButton","roleHeading":"Instance Property"},"abstract":[{"text":"A Boolean value that determines whether the default iAdvize SDK chat button is used.","type":"text"}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController\/useDefaultFloatingButton","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/usedefaultfloatingbutton"]},{"paths":["\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/usedefaultfloatingbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController/useDefaultFloatingButton":{"abstract":[{"type":"text","text":"A Boolean value that determines whether the default iAdvize SDK chat button is used."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"useDefaultFloatingButton","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController\/useDefaultFloatingButton","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/usedefaultfloatingbutton","title":"useDefaultFloatingButton","kind":"symbol","type":"topic","navigatorTitle":[{"text":"useDefaultFloatingButton","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatboxController"}],"title":"ChatboxController","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","abstract":[{"text":"An object that controls the chatbox, which is where the conversation is displayed, and the chat button.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatboxController","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"useDefaultFloatingButton","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"useDefaultFloatingButton"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"useDefaultFloatingButton","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController~1useDefaultFloatingButton\/title","value":"useDefaultFloatingButton"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController~1useDefaultFloatingButton\/fragments","op":"replace","value":[{"text":"useDefaultFloatingButton","kind":"identifier"}]},{"op":"replace","value":"ChatboxController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments","value":[{"text":"ChatboxController","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatboxController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}