{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","text":"ConversationChannel"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/init(id:conversationChannel:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingrule\/init(id:conversationchannel:)"]}],"kind":"symbol","metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"init","externalID":"s:22IAdvizeConversationSDK13TargetingRuleC2id19conversationChannelAC10Foundation4UUIDV_AA0bH0Otcfc","role":"symbol","title":"init(id:conversationChannel:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationChannel","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","url":"\/documentation\/iadvizeconversationsdk\/targetingrule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"abstract":[],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","title":"ConversationChannel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationChannel","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule/init(id:conversationChannel:)":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/init(id:conversationChannel:)","type":"topic","title":"init(id:conversationChannel:)","url":"\/documentation\/iadvizeconversationsdk\/targetingrule\/init(id:conversationchannel:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV","text":"UUID"},{"text":", ","kind":"text"},{"text":"conversationChannel","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationChannel","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","value":"TargetingRule"},{"op":"replace","value":[{"kind":"identifier","text":"TargetingRule"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TargetingRule"}]}]}]}