{"kind":"symbol","metadata":{"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule(im)initWithId:objcConversationChannel:","roleHeading":"Instance Method","title":"initWithId:objcConversationChannel:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:objcConversationChannel:"}],"navigatorTitle":[{"text":"initWithId:objcConversationChannel:","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSUUID","text":"NSUUID","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"id"},{"kind":"text","text":" "},{"text":"objcConversationChannel:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationChannel","text":"ConversationChannel","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-c.class","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"objcConversationChannel","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/initWithId:objcConversationChannel:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingrule\/initwithid:objcconversationchannel:"]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule/initWithId:objcConversationChannel:":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/initWithId:objcConversationChannel:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithId:objcConversationChannel:"}],"title":"initWithId:objcConversationChannel:","url":"\/documentation\/iadvizeconversationsdk\/targetingrule\/initwithid:objcconversationchannel:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithId:objcConversationChannel:"}],"abstract":[],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-c.class":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-c.class","fragments":[{"kind":"identifier","text":"ConversationChannel"}],"abstract":[],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-c.class","title":"ConversationChannel","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","url":"\/documentation\/iadvizeconversationsdk\/targetingrule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","value":"TargetingRule","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","value":[{"text":"TargetingRule","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TargetingRule"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle"}]}]}