{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationControllerDelegate","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(pl)ConversationControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontroller\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontroller\/delegate"]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController\/delegate","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The object notified of events related to the conversation such as new messages received.","type":"text"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"text":"ConversationControllerDelegate","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(pl)ConversationControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController(py)delegate"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","type":"topic","role":"symbol","title":"ConversationController","navigatorTitle":[{"text":"ConversationController","kind":"identifier"}],"abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationController","kind":"identifier"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController/delegate":{"role":"symbol","title":"delegate","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(pl)ConversationControllerDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller\/delegate","abstract":[{"type":"text","text":"The object notified of events related to the conversation such as new messages received."}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationControllerDelegate"}],"abstract":[{"text":"An object that is notified about the ongoing conversation.","type":"text"}],"title":"ConversationControllerDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConversationControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@IAdvizeConversationSDK@objc(pl)ConversationControllerDelegate","text":"id<ConversationControllerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title","value":"ConversationController","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments","op":"replace","value":[{"text":"ConversationController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle","value":[{"text":"ConversationController","kind":"identifier"}],"op":"replace"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController~1delegate\/fragments","op":"replace"},{"op":"replace","value":"ConversationControllerDelegate","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/fragments","value":[{"text":"ConversationControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationControllerDelegate"}]}]}]}