{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ongoingConversation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation","text":"OngoingConversation","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)OngoingConversation"},{"kind":"text","text":"?"}]}]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController\/ongoingConversation()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ongoingConversation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"OngoingConversation","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)OngoingConversation"},{"text":"?","kind":"text"}],"title":"ongoingConversation()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"ongoingConversation"}],"role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"roleHeading":"Instance Method","externalID":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController(im)ongoingConversation"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontroller\/ongoingconversation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontroller\/ongoingconversation()"]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController/ongoingConversation()":{"role":"symbol","title":"ongoingConversation()","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController\/ongoingConversation()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ongoingConversation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"OngoingConversation","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)OngoingConversation"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"ongoingConversation","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller\/ongoingconversation()","abstract":[],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation":{"role":"symbol","title":"OngoingConversation","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OngoingConversation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"OngoingConversation","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation","abstract":[],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","type":"topic","role":"symbol","title":"ConversationController","navigatorTitle":[{"text":"ConversationController","kind":"identifier"}],"abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationController","kind":"identifier"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"ongoingConversation","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"ongoingConversation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)OngoingConversation","kind":"typeIdentifier","text":"OngoingConversation"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"ongoingConversation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController~1ongoingConversation()\/title","op":"replace","value":"ongoingConversation"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController~1ongoingConversation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ongoingConversation"}],"op":"replace"},{"op":"replace","value":"OngoingConversation","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/title"},{"value":[{"text":"OngoingConversation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/fragments"},{"value":[{"kind":"identifier","text":"OngoingConversation"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title","value":"ConversationController"},{"value":[{"kind":"identifier","text":"ConversationController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}