{
  "abstract" : [
    {
      "text" : "The amount of the transaction.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/amount"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:22IAdvizeConversationSDK11TransactionC6amountSdvp",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "let"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "amount"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:Sd",
        "text" : "Double"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Property",
    "symbolKind" : "property",
    "title" : "amount"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "let"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "amount"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:Sd",
              "text" : "Double"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/transaction\/amount"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction": {
  "abstract" : [
    {
      "text" : "Describes a visitor transaction.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "Transaction"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "Transaction"
    }
  ],
  "role" : "symbol",
  "title" : "Transaction",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/transaction"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/amount": {
  "abstract" : [
    {
      "text" : "The amount of the transaction.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "let"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "amount"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sd",
      "text" : "Double"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/amount",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "amount",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/transaction\/amount"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title",
        "value" : "Transaction"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Transaction"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "Transaction"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}