{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithExternalTransactionId:date:amount:currency:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithExternalTransactionId:date:amount:currency:"}],"title":"initWithExternalTransactionId:date:amount:currency:","externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)Transaction(im)initWithExternalTransactionId:date:amount:currency:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"IAdvizeConversationSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithExternalTransactionId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"externalTransactionId"},{"text":" ","kind":"text"},{"text":"date:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"date"},{"text":" ","kind":"text"},{"text":"amount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"amount"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLCurrency","preciseIdentifier":"c:@M@IAdvizeConversationSDK@E@GraphQLCurrency","kind":"typeIdentifier","text":"GraphQLCurrency"},{"text":") ","kind":"text"},{"text":"currency","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/initWithExternalTransactionId:date:amount:currency:","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/transaction\/initwithexternaltransactionid:date:amount:currency:"]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GraphQLCurrency":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLCurrency","url":"\/documentation\/iadvizeconversationsdk\/graphqlcurrency","fragments":[{"kind":"identifier","text":"GraphQLCurrency"}],"title":"GraphQLCurrency","role":"symbol","abstract":[{"type":"text","text":"ISO4217 currency code."}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"title":"Transaction","navigatorTitle":[{"text":"Transaction","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","type":"topic","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Transaction"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/initWithExternalTransactionId:date:amount:currency:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithExternalTransactionId:date:amount:currency:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/transaction\/initwithexternaltransactionid:date:amount:currency:","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/initWithExternalTransactionId:date:amount:currency:","abstract":[],"role":"symbol","title":"initWithExternalTransactionId:date:amount:currency:","navigatorTitle":[{"text":"initWithExternalTransactionId:date:amount:currency:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title","value":"Transaction"},{"op":"replace","value":[{"text":"Transaction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments"},{"value":[{"text":"Transaction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle"}]}]}