{"metadata":{"externalID":"c:@M@IAdvizeConversationSDK@objc(pl)ConversationControllerDelegate(im)conversationController:shouldOpen:","symbolKind":"method","roleHeading":"Instance Method","title":"conversationController(_:shouldOpen:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"conversationController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController","kind":"typeIdentifier","text":"ConversationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldOpen"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"IAdvizeConversationSDK"}],"navigatorTitle":[{"text":"conversationController:shouldOpen:","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"Called on the delegate when the user has tapped on a link to ask whether the URL should be opened.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/conversationController(_:shouldOpen:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"ConversationController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController"},{"text":", ","kind":"text"},{"text":"shouldOpen","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The object managing the conversation."}],"type":"paragraph"}],"name":"controller"},{"content":[{"inlineContent":[{"type":"text","text":"The URL to be processed."}],"type":"paragraph"}],"name":"url"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"true","type":"codeVoice"},{"text":" if the URL should be opened; ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" if you want to handle the URL yourself."}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Implementation of this method is optional. By default, the iAdvize SDK opens the URL in a","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"SFSafariViewController"},{"text":".","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate\/conversationcontroller(_:shouldopen:)"]},{"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate\/conversationcontroller(_:shouldopen:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate/conversationController(_:shouldOpen:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/conversationController(_:shouldOpen:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"conversationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConversationController","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldOpen"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate\/conversationcontroller(_:shouldopen:)","navigatorTitle":[{"kind":"identifier","text":"conversationController:shouldOpen:"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Called on the delegate when the user has tapped on a link to ask whether the URL should be opened."}],"title":"conversationController(_:shouldOpen:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate","title":"ConversationControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationControllerDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"abstract":[{"text":"An object that is notified about the ongoing conversation.","type":"text"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationController"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","navigatorTitle":[{"kind":"identifier","text":"ConversationController"}],"type":"topic","role":"symbol","abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"title":"ConversationController"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"conversationController:shouldOpen:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"conversationController:shouldOpen:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"conversationController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConversationController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController"},{"kind":"text","text":" *) "},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"text":"shouldOpen:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The object managing the conversation.","type":"text"}],"type":"paragraph"}],"name":"controller"},{"name":"url","content":[{"type":"paragraph","inlineContent":[{"text":"The URL to be processed.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"true"},{"text":" if the URL should be opened; ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" if you want to handle the URL yourself."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1conversationController(_:shouldOpen:)\/title","value":"conversationController:shouldOpen:"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1conversationController(_:shouldOpen:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"conversationController:shouldOpen:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/title","value":"ConversationControllerDelegate"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/fragments","op":"replace","value":[{"text":"ConversationControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title","value":"ConversationController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments","value":[{"kind":"identifier","text":"ConversationController"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}