{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/currency"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/transaction\/currency"]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"]]},"kind":"symbol","abstract":[{"type":"text","text":"The currency of the transaction."}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"s:22IAdvizeConversationSDK11TransactionC8currencyAA8CurrencyOvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency"},{"text":": ","kind":"text"},{"text":"Currency","preciseIdentifier":"s:22IAdvizeConversationSDK8CurrencyO","kind":"typeIdentifier"}],"title":"currency","modules":[{"name":"IAdvizeConversationSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency","preciseIdentifier":"s:22IAdvizeConversationSDK8CurrencyO","kind":"typeIdentifier","text":"Currency"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Transaction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Transaction"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"title":"Transaction","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Currency":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Currency"}],"navigatorTitle":[{"kind":"identifier","text":"Currency"}],"abstract":[{"type":"text","text":"Currency used in a "},{"type":"codeVoice","code":"Transaction"},{"type":"text","text":"."}],"title":"Currency","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency","url":"\/documentation\/iadvizeconversationsdk\/currency","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/currency":{"abstract":[{"text":"The currency of the transaction.","type":"text"}],"title":"currency","kind":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/transaction\/currency","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency"},{"text":": ","kind":"text"},{"text":"Currency","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK8CurrencyO"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/currency"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title","op":"replace","value":"Transaction"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments","op":"replace","value":[{"text":"Transaction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle","value":[{"kind":"identifier","text":"Transaction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}