{"abstract":[{"type":"text","text":"A unique identifier for the transaction."}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/externalTransactionId","interfaceLanguage":"swift"},"metadata":{"externalID":"s:22IAdvizeConversationSDK11TransactionC08externalD2IdSSvp","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"externalTransactionId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"externalTransactionId","symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalTransactionId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/transaction\/externaltransactionid"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Transaction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Transaction"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"title":"Transaction","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction/externalTransactionId":{"url":"\/documentation\/iadvizeconversationsdk\/transaction\/externaltransactionid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"externalTransactionId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction\/externalTransactionId","title":"externalTransactionId","role":"symbol","abstract":[{"type":"text","text":"A unique identifier for the transaction."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title","value":"Transaction"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments","op":"replace","value":[{"text":"Transaction","kind":"identifier"}]},{"value":[{"text":"Transaction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}