{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/setLanguage:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)TargetingController(im)setLanguage:","navigatorTitle":[{"kind":"identifier","text":"setLanguage:"}],"title":"setLanguage:","fragments":[{"kind":"text","text":"- "},{"text":"setLanguage:","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setLanguage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SDKLanguageOption","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)SDKLanguageOption","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-c.class"},{"text":" *) ","kind":"text"},{"text":"language","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontroller\/setlanguage:"]}],"kind":"symbol","references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingController"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingController"}],"title":"TargetingController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController/setLanguage:":{"abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setLanguage:"}],"title":"setLanguage:","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller\/setlanguage:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setLanguage:"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController\/setLanguage:"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-c.class":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-c.class","abstract":[],"title":"SDKLanguageOption","kind":"symbol","fragments":[{"text":"SDKLanguageOption","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-c.class","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title","value":"TargetingController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","op":"replace","value":[{"text":"TargetingController","kind":"identifier"}]},{"op":"replace","value":[{"text":"TargetingController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle"}]}]}