{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"text":"(","kind":"text"},{"text":"projectId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"authenticationOption","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK20AuthenticationOptionO","text":"AuthenticationOption","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"gdprOption","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GDPROption","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK10GDPROptionO"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"success","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"s:22IAdvizeConversationSDK0aC0C8activate9projectId20authenticationOption04gdprH010completionySi_AA014AuthenticationH0OAA10GDPROptionOySbcSgtF","roleHeading":"Instance Method","title":"activate(projectId:authenticationOption:gdprOption:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activate(projectId:authenticationOption:gdprOption:completion:)"},"abstract":[{"text":"Activate the iAdvize SDK for the visitor.","type":"text"}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activate(projectid:authenticationoption:gdproption:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"("},{"text":"projectId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"authenticationOption","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","kind":"typeIdentifier","text":"AuthenticationOption","preciseIdentifier":"s:22IAdvizeConversationSDK20AuthenticationOptionO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"gdprOption"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK10GDPROptionO","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","kind":"typeIdentifier","text":"GDPROption"},{"kind":"text","text":" = .disabled, "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"projectId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Id of the project."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The option of authentication of the visitor, anonymous or simple."}],"type":"paragraph"}],"name":"authenticationOption"},{"name":"gdprOption","content":[{"type":"paragraph","inlineContent":[{"text":"The option defining the behavior regarding the GDPR message that can be displayed at the","type":"text"},{"type":"text","text":" "},{"text":"beginning of the conversation.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler called when the activation process is done. The "},{"code":"success","type":"codeVoice"},{"text":" value indicates","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"if the activation process was successful."}]}]}]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/activate(projectId:authenticationOption:gdprOption:completion:)":{"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activate(projectid:authenticationoption:gdproption:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"projectId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"authenticationOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AuthenticationOption","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK20AuthenticationOptionO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gdprOption"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK10GDPROptionO","text":"GDPROption","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"success","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activate(projectId:authenticationOption:gdprOption:completion:)","role":"symbol","type":"topic","title":"activate(projectId:authenticationOption:gdprOption:completion:)","abstract":[{"text":"Activate the iAdvize SDK for the visitor.","type":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAdvizeSDK","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","title":"IAdvizeSDK","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"kind":"symbol","type":"topic","title":"GDPROption","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"role":"symbol","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationOption"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The option to authenticate the visitor."}],"title":"AuthenticationOption","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","role":"symbol","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","op":"replace","value":"IAdvizeSDK"},{"op":"replace","value":[{"kind":"identifier","text":"IAdvizeSDK"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle","value":[{"kind":"identifier","text":"IAdvizeSDK"}],"op":"replace"}]}]}