{"metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"title":"debugInfo()","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"debugInfo"}],"role":"symbol","externalID":"c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(im)debugInfo","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugInfo"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"sections":[],"abstract":[{"type":"text","text":"Returns a JSON "},{"type":"codeVoice","code":"String"},{"text":" containing detailed information about the current state of the iAdvize SDK.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/debugInfo()"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugInfo"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"A JSON ","type":"text"},{"code":"String","type":"codeVoice"},{"type":"text","text":" representing the current state of the SDK."}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is intended for debugging purposes only and should be used to assist in diagnosing issues with the"},{"text":" ","type":"text"},{"text":"SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can include the returned string in your logs, and share it with iAdvize support for further analysis of any"},{"text":" ","type":"text"},{"text":"encountered problems.","type":"text"}]},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Important:","type":"text"}],"type":"strong"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The structure and content of the JSON string may change without notice. Do not rely on it for any","type":"text"},{"type":"text","text":" "},{"type":"text","text":"functionality in your application."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Do not attempt to parse or manipulate the JSON string; it is meant solely for debugging and support purposes."}]}]}],"type":"unorderedList"}]}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/debuginfo()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/debuginfo()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/debugInfo()":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/debugInfo()","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/debuginfo()","kind":"symbol","title":"debugInfo()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"debugInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"debugInfo","kind":"identifier"}],"abstract":[{"text":"Returns a JSON ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" containing detailed information about the current state of the iAdvize SDK."}],"role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAdvizeSDK","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","title":"IAdvizeSDK","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"debugInfo"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"debugInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"debugInfo","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A JSON "},{"code":"String","type":"codeVoice"},{"type":"text","text":" representing the current state of the SDK."}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1debugInfo()\/title","value":"debugInfo","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"debugInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1debugInfo()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","value":"IAdvizeSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","value":[{"kind":"identifier","text":"IAdvizeSDK"}]},{"value":[{"kind":"identifier","text":"IAdvizeSDK"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle"}]}]}