{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"logout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This hides the chat button, disables push notifications and clears all the locally stored visitor data."},{"type":"text","text":" "},{"type":"text","text":"You will need to call activate again if the user needs to start a new conversation."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Logout the visitor from the iAdvize SDK."}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/logout(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/logout(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logout(completion:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(im)logoutWithCompletion:","title":"logout(completion:)","navigatorTitle":[{"text":"logoutWithCompletion:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"IAdvizeConversationSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","title":"IAdvizeSDK","abstract":[{"type":"text","text":"The iAdvize SDK lets you provide a unique conversational experience to your users."}],"role":"symbol","navigatorTitle":[{"text":"IAdvizeSDK","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IAdvizeSDK","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/logout(completion:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logout(completion:)","abstract":[{"type":"text","text":"Logout the visitor from the iAdvize SDK."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logout"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"kind":"identifier","text":"logoutWithCompletion:"}],"kind":"symbol","title":"logout(completion:)","role":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/logout(completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"logoutWithCompletion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"logoutWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"logoutWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"IAdvizeSDK","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","op":"replace","value":[{"text":"IAdvizeSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle","value":[{"kind":"identifier","text":"IAdvizeSDK"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1logout(completion:)\/title","value":"logoutWithCompletion:"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1logout(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logoutWithCompletion:","kind":"identifier"}],"op":"replace"}]}]}