{"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/setloglevel:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"metadata":{"roleHeading":"Instance Method","externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(im)setLogLevel:","fragments":[{"text":"- ","kind":"text"},{"text":"setLogLevel:","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setLogLevel:"}],"symbolKind":"method","title":"setLogLevel:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/setLogLevel:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setLogLevel:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"LoggerLogLevel","preciseIdentifier":"c:@M@IAdvizeConversationSDK@E@LoggerLogLevel","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/LoggerLogLevel"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"logLevel"},{"text":";","kind":"text"}]}]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/setLogLevel:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"setLogLevel:","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/setloglevel:","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/setLogLevel:","type":"topic","role":"symbol","navigatorTitle":[{"text":"setLogLevel:","kind":"identifier"}],"abstract":[],"title":"setLogLevel:"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/LoggerLogLevel":{"url":"\/documentation\/iadvizeconversationsdk\/loggerloglevel","title":"LoggerLogLevel","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"LoggerLogLevel"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/LoggerLogLevel"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","title":"IAdvizeSDK","abstract":[{"type":"text","text":"The iAdvize SDK lets you provide a unique conversational experience to your users."}],"role":"symbol","navigatorTitle":[{"text":"IAdvizeSDK","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IAdvizeSDK","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","value":"IAdvizeSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","value":[{"text":"IAdvizeSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle","value":[{"text":"IAdvizeSDK","kind":"identifier"}],"op":"replace"}]}]}