{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationChannel"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO","kind":"typeIdentifier","text":"ConversationChannel"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","title":"conversationChannel","symbolKind":"property","externalID":"s:22IAdvizeConversationSDK07OngoingB0C19conversationChannelAA0bF0Ovp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"conversationChannel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationChannel","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO","kind":"typeIdentifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/ongoingconversation\/conversationchannel"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation\/conversationChannel"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","title":"ConversationChannel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationChannel","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation/conversationChannel":{"role":"symbol","title":"conversationChannel","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation\/conversationChannel","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationChannel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO","text":"ConversationChannel"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation\/conversationchannel","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation":{"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OngoingConversation","kind":"identifier"}],"navigatorTitle":[{"text":"OngoingConversation","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"OngoingConversation","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"}},"variantOverrides":[{"patch":[{"value":"OngoingConversation","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/fragments","value":[{"text":"OngoingConversation","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"OngoingConversation"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}