{"metadata":{"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)NotificationController(im)clearIAdvizePushNotifications","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearIAdvizePushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"clearIAdvizePushNotifications"}],"title":"clearIAdvizePushNotifications()","modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/notificationcontroller\/cleariadvizepushnotifications()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/notificationcontroller\/cleariadvizepushnotifications()"]}],"sections":[],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/clearIAdvizePushNotifications()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Clears the iAdvize SDK push notifications from the Notification Center."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearIAdvizePushNotifications"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/clearIAdvizePushNotifications()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearIAdvizePushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/clearIAdvizePushNotifications()","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/cleariadvizepushnotifications()","role":"symbol","navigatorTitle":[{"text":"clearIAdvizePushNotifications","kind":"identifier"}],"title":"clearIAdvizePushNotifications()","abstract":[{"type":"text","text":"Clears the iAdvize SDK push notifications from the Notification Center."}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController","navigatorTitle":[{"kind":"identifier","text":"NotificationController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller","title":"NotificationController","role":"symbol","abstract":[{"type":"text","text":"An object that allows to configure push notifications."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"clearIAdvizePushNotifications"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearIAdvizePushNotifications"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearIAdvizePushNotifications"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1clearIAdvizePushNotifications()\/title","value":"clearIAdvizePushNotifications"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearIAdvizePushNotifications"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1clearIAdvizePushNotifications()\/fragments"},{"value":"NotificationController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NotificationController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/navigatorTitle","value":[{"text":"NotificationController","kind":"identifier"}],"op":"replace"}]}]}