{"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"registerPushToken:applicationMode:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"registerPushToken:applicationMode:","navigatorTitle":[{"kind":"identifier","text":"registerPushToken:applicationMode:"}],"externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)NotificationController(im)registerPushToken:applicationMode:","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerPushToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pushToken","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GraphQLApplicationMode","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLApplicationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@E@GraphQLApplicationMode"},{"text":") ","kind":"text"},{"text":"applicationMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken:applicationMode:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/notificationcontroller\/registerpushtoken:applicationmode:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GraphQLApplicationMode":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLApplicationMode","title":"GraphQLApplicationMode","fragments":[{"kind":"identifier","text":"GraphQLApplicationMode"}],"url":"\/documentation\/iadvizeconversationsdk\/graphqlapplicationmode"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/registerPushToken:applicationMode:":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken:applicationMode:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerPushToken:applicationMode:"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/registerpushtoken:applicationmode:","type":"topic","title":"registerPushToken:applicationMode:","role":"symbol","navigatorTitle":[{"text":"registerPushToken:applicationMode:","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController","navigatorTitle":[{"kind":"identifier","text":"NotificationController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller","title":"NotificationController","role":"symbol","abstract":[{"type":"text","text":"An object that allows to configure push notifications."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/title","value":"NotificationController"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/fragments"},{"value":[{"kind":"identifier","text":"NotificationController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}