{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController"]]},"abstract":[{"type":"text","text":"Register the push token of your visitor device so it will receive push notifications for new messages received"},{"type":"text","text":" "},{"text":"during the conversation.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerPushToken"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22IAdvizeConversationSDK15ApplicationModeO","kind":"typeIdentifier","text":"ApplicationMode"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","externalID":"s:22IAdvizeConversationSDK22NotificationControllerC17registerPushToken_15applicationModeySS_AA011ApplicationJ0OtF","title":"registerPushToken(_:applicationMode:)","modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerPushToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pushToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"applicationMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ApplicationMode","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode","preciseIdentifier":"s:22IAdvizeConversationSDK15ApplicationModeO","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The push token of the device which will be associated to the current visitor identifier."}]}],"name":"pushToken"},{"name":"applicationMode","content":[{"inlineContent":[{"type":"text","text":"The current running mode of the application. Used to properly send push notifications on"},{"type":"text","text":" "},{"type":"text","text":"the right APNS server (sandbox\/production)."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Push notifications are enabled by default for the user as long as you have registered a push token.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you want to disable all push notifications from the iAdvize SDK you have to call"},{"text":" ","type":"text"},{"type":"codeVoice","code":"IAdvizeSDK.notificationController.disablePushNotifications()"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can use preprocessor flags to manage both application mode while integrating the SDK:","type":"text"}]},{"type":"codeListing","code":["   #if DEBUG","   IAdvizeSDK.shared.notificationController.registerPushToken(pushToken, applicationMode: .dev)","   #else","   IAdvizeSDK.shared.notificationController.registerPushToken(pushToken, applicationMode: .prod)","   #endif"],"syntax":null}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken(_:applicationMode:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/notificationcontroller\/registerpushtoken(_:applicationmode:)"]}],"sections":[],"kind":"symbol","references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/registerPushToken(_:applicationMode:)":{"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken(_:applicationMode:)","abstract":[{"text":"Register the push token of your visitor device so it will receive push notifications for new messages received","type":"text"},{"type":"text","text":" "},{"text":"during the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK15ApplicationModeO","text":"ApplicationMode"},{"text":")","kind":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/registerpushtoken(_:applicationmode:)","kind":"symbol","type":"topic","title":"registerPushToken(_:applicationMode:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController","navigatorTitle":[{"kind":"identifier","text":"NotificationController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller","title":"NotificationController","role":"symbol","abstract":[{"type":"text","text":"An object that allows to configure push notifications."}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode":{"navigatorTitle":[{"text":"ApplicationMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Mode for APNS."}],"title":"ApplicationMode","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApplicationMode"}],"url":"\/documentation\/iadvizeconversationsdk\/applicationmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/title","value":"NotificationController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/fragments","value":[{"text":"NotificationController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NotificationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}