{
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/init(id:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:22IAdvizeConversationSDK13TargetingRuleC2idAC10Foundation4UUIDV_tcfc",
    "fragments" : [
      {
        "kind" : "identifier",
        "text" : "init"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "externalParam",
        "text" : "id"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:10Foundation4UUIDV",
        "text" : "UUID"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Initializer",
    "symbolKind" : "init",
    "title" : "init(id:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "init"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "id"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:10Foundation4UUIDV",
              "text" : "UUID"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/targetingrule\/init(id:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TargetingRule"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TargetingRule"
    }
  ],
  "role" : "symbol",
  "title" : "TargetingRule",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingrule"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule/init(id:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "id"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:10Foundation4UUIDV",
      "text" : "UUID"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/init(id:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(id:)",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingrule\/init(id:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title",
        "value" : "TargetingRule"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingRule"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingRule"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}