{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/activateNewRule(targetingRule:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"activateNewRule","kind":"identifier"},{"kind":"text","text":"("},{"text":"targetingRule","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","text":"TargetingRule"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum"]]},"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum\/activatenewrule(targetingrule:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"activateNewRule","kind":"identifier"},{"text":"(","kind":"text"},{"text":"targetingRule","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","text":"TargetingRule","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"case","title":"NavigationOption.activateNewRule(targetingRule:)","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"s:22IAdvizeConversationSDK16NavigationOptionO15activateNewRuleyAcA09TargetingH0C_tcACmF"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","url":"\/documentation\/iadvizeconversationsdk\/targetingrule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"abstract":[],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","navigatorTitle":[{"kind":"identifier","text":"NavigationOption"}],"title":"NavigationOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NavigationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum/activateNewRule(targetingRule:)":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/activateNewRule(targetingRule:)","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"activateNewRule","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"targetingRule"},{"text":": ","kind":"text"},{"text":"TargetingRule","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule"},{"text":")","kind":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum\/activatenewrule(targetingrule:)","role":"symbol","title":"NavigationOption.activateNewRule(targetingRule:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","op":"replace","value":"TargetingRule"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","value":[{"text":"TargetingRule","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","value":[{"kind":"identifier","text":"TargetingRule"}]}]}]}