{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","title":"init","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)VisitorController(im)init","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/visitorcontroller\/init"]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController/init":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/init","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller\/init","title":"init"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VisitorController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitorController","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller","role":"symbol","kind":"symbol","title":"VisitorController"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/title","value":"VisitorController","op":"replace"},{"value":[{"kind":"identifier","text":"VisitorController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/navigatorTitle","op":"replace","value":[{"text":"VisitorController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}