{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"registerCustomData(customData:completion:)","role":"symbol","externalID":"s:22IAdvizeConversationSDK17VisitorControllerC18registerCustomData06customH010completionySDySSAA0gH0OG_ySbcSgtF","modules":[{"name":"IAdvizeConversationSDK"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerCustomData"},{"text":"(","kind":"text"},{"text":"customData","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"CustomData","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK10CustomDataO"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}]},"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/visitorcontroller\/registercustomdata(customdata:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Send a list of Visitor Custom Data."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/registerCustomData(customData:completion:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerCustomData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customData"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData","text":"CustomData","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK10CustomDataO"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"customData","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Map which contains the list of value key."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The block to execute when after the custom data have been sent.","type":"text"},{"type":"text","text":" "},{"text":"Please visit https:\/\/github.com\/iadvize\/iadvize-android-sdk for further information.","type":"text"}]}],"name":"completion"}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"A visitor custom data is a key value pair linked to a visitor and whose valorization"},{"text":" ","type":"text"},{"type":"text","text":"is at the initiative of the integrator."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitorController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","title":"VisitorController","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VisitorController"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData":{"type":"topic","title":"CustomData","url":"\/documentation\/iadvizeconversationsdk\/customdata","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData","kind":"symbol","navigatorTitle":[{"text":"CustomData","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomData","kind":"identifier"}],"abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController/registerCustomData(customData:completion:)":{"abstract":[{"type":"text","text":"Send a list of Visitor Custom Data."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerCustomData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customData"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK10CustomDataO","text":"CustomData","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller\/registercustomdata(customdata:completion:)","type":"topic","title":"registerCustomData(customData:completion:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/registerCustomData(customData:completion:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"VisitorController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/fragments","value":[{"kind":"identifier","text":"VisitorController"}]},{"op":"replace","value":[{"text":"VisitorController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/navigatorTitle"}]}]}