{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didTapMoreInformation"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/gdprdelegate\/didtapmoreinformation()"]},{"paths":["\/documentation\/iadvizeconversationsdk\/gdprdelegate\/didtapmoreinformation()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Called when the visitor tap on ‘More information’ in the GDPR message."}],"metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(pl)GDPRDelegate(im)didTapMoreInformation","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapMoreInformation"},{"kind":"text","text":"()"}],"title":"didTapMoreInformation()","roleHeading":"Instance Method","navigatorTitle":[{"text":"didTapMoreInformation","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate\/didTapMoreInformation()"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate/didTapMoreInformation()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapMoreInformation"},{"kind":"text","text":"()"}],"required":true,"kind":"symbol","type":"topic","title":"didTapMoreInformation()","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate\/didtapmoreinformation()","abstract":[{"text":"Called when the visitor tap on ‘More information’ in the GDPR message.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"didTapMoreInformation","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate\/didTapMoreInformation()"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GDPRDelegate","kind":"identifier"}],"title":"GDPRDelegate","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","abstract":[{"type":"text","text":"An object that is notified about visitor interaction with the GDRP message."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPRDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"didTapMoreInformation","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapMoreInformation"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"didTapMoreInformation","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"didTapMoreInformation","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate~1didTapMoreInformation()\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate~1didTapMoreInformation()\/fragments","value":[{"kind":"text","text":"- "},{"text":"didTapMoreInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"GDPRDelegate","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments","value":[{"kind":"identifier","text":"GDPRDelegate"}]},{"value":[{"text":"GDPRDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle"}]}]}