{
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "occ",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activateWithProjectId:authenticationOption:gdprOption:completion:"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@CM@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(im)activateWithProjectId:authenticationOption:gdprOption:completion:",
    "fragments" : [
      {
        "kind" : "text",
        "text" : "- "
      },
      {
        "kind" : "identifier",
        "text" : "activateWithProjectId:authenticationOption:gdprOption:completion:"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "activateWithProjectId:authenticationOption:gdprOption:completion:"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Method",
    "symbolKind" : "method",
    "title" : "activateWithProjectId:authenticationOption:gdprOption:completion:"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "occ"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "text",
              "text" : "- ("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:v",
              "text" : "void"
            },
            {
              "kind" : "text",
              "text" : ") "
            },
            {
              "kind" : "identifier",
              "text" : "activateWithProjectId:"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@T@NSInteger",
              "text" : "NSInteger"
            },
            {
              "kind" : "text",
              "text" : ") "
            },
            {
              "kind" : "internalParam",
              "text" : "projectId"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "authenticationOption:"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-c.class",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)AuthenticationOption",
              "text" : "AuthenticationOption"
            },
            {
              "kind" : "text",
              "text" : " *) "
            },
            {
              "kind" : "internalParam",
              "text" : "authenticationOption"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "gdprOption:"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-c.class",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)GDPROption",
              "text" : "GDPROption"
            },
            {
              "kind" : "text",
              "text" : " *) "
            },
            {
              "kind" : "internalParam",
              "text" : "gdprOption"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "completion:"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:v",
              "text" : "void"
            },
            {
              "kind" : "text",
              "text" : " (^"
            },
            {
              "kind" : "text",
              "text" : ")("
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@T@BOOL",
              "text" : "BOOL"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : ""
            },
            {
              "kind" : "text",
              "text" : ")) "
            },
            {
              "kind" : "internalParam",
              "text" : "completion"
            },
            {
              "kind" : "text",
              "text" : ";"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activatewithprojectid:authenticationoption:gdproption:completion:"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-c.class": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "AuthenticationOption"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-c.class",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "AuthenticationOption",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/authenticationoption-c.class"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-c.class": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "GDPROption"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-c.class",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "GDPROption",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/gdproption-c.class"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK": {
  "abstract" : [
    {
      "text" : "The iAdvize SDK lets you provide a unique conversational experience to your users.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "IAdvizeSDK"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "IAdvizeSDK"
    }
  ],
  "role" : "symbol",
  "title" : "IAdvizeSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/iadvizesdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/activateWithProjectId:authenticationOption:gdprOption:completion:": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "text",
      "text" : "- "
    },
    {
      "kind" : "identifier",
      "text" : "activateWithProjectId:authenticationOption:gdprOption:completion:"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activateWithProjectId:authenticationOption:gdprOption:completion:",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "activateWithProjectId:authenticationOption:gdprOption:completion:"
    }
  ],
  "role" : "symbol",
  "title" : "activateWithProjectId:authenticationOption:gdprOption:completion:",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activatewithprojectid:authenticationoption:gdproption:completion:"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title",
        "value" : "IAdvizeSDK"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "IAdvizeSDK"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "IAdvizeSDK"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}