{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/conversationcontroller"]},{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/conversationcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/conversationController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object that allows to monitor the conversation."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"conversationController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController","text":"ConversationController","kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"metadata":{"title":"conversationController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"conversationController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController","text":"ConversationController"}],"navigatorTitle":[{"text":"conversationController","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(py)conversationController","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/conversationController":{"title":"conversationController","type":"topic","role":"symbol","navigatorTitle":[{"text":"conversationController","kind":"identifier"}],"abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"conversationController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController","text":"ConversationController","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/conversationcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/conversationController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","type":"topic","role":"symbol","title":"ConversationController","navigatorTitle":[{"text":"ConversationController","kind":"identifier"}],"abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationController","kind":"identifier"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"kind":"symbol","title":"IAdvizeSDK","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"conversationController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"conversationController"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController","text":"ConversationController","kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController"},{"kind":"text","text":" * "},{"text":"conversationController","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1conversationController\/title","value":"conversationController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1conversationController\/fragments","value":[{"text":"conversationController","kind":"identifier"}],"op":"replace"},{"value":"ConversationController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title"},{"value":[{"text":"ConversationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments"},{"value":[{"text":"ConversationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle"},{"value":"IAdvizeSDK","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","op":"replace"},{"value":[{"text":"IAdvizeSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments"},{"op":"replace","value":[{"text":"IAdvizeSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}