{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Logger","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger","preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO"},{"kind":"text","text":"."},{"text":"LogLevel","preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO8LogLevelO","kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger\/LogLevel"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"By default, the iAdvize SDK will only log the ","type":"text"},{"type":"codeVoice","code":"warning"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"error"},{"type":"text","text":" message in the console. You can change"},{"type":"text","text":" "},{"text":"this value to have more feedbacks on the iAdvize SDK activity.","type":"text"}]}]}],"abstract":[{"text":"The log level of the iAdvize SDK console logger.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/loglevel"]}],"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:22IAdvizeConversationSDK0aC0C8logLevelAA6LoggerO03LogE0Ovp","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"title":"logLevel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO","kind":"typeIdentifier","text":"Logger"},{"text":".","kind":"text"},{"text":"LogLevel","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO8LogLevelO"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logLevel"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"kind":"symbol","title":"IAdvizeSDK","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Logger/LogLevel":{"abstract":[{"type":"text","text":"Level of a logged message."}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger\/LogLevel","role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"title":"Logger.LogLevel","url":"\/documentation\/iadvizeconversationsdk\/logger\/loglevel"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Logger":{"abstract":[{"text":"Main structure that is used to log all messages.","type":"text"}],"title":"Logger","type":"topic","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/logger","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/logLevel":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logLevel","kind":"symbol","abstract":[{"type":"text","text":"The log level of the iAdvize SDK console logger."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO","text":"Logger"},{"kind":"text","text":"."},{"preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO8LogLevelO","text":"LogLevel","kind":"typeIdentifier"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/loglevel","role":"symbol","title":"logLevel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","value":"IAdvizeSDK"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","op":"replace","value":[{"kind":"identifier","text":"IAdvizeSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle","value":[{"text":"IAdvizeSDK","kind":"identifier"}]}]}]}