{
  "abstract" : [
    {
      "text" : "An object that allows to configure and monitor the targeting process.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/targetingController"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(py)targetingController",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "var"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "targetingController"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)TargetingController",
        "text" : "TargetingController"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "targetingController"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Instance Property",
    "symbolKind" : "property",
    "title" : "targetingController"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "attribute",
              "text" : "@objc"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "lazy"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "var"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "targetingController"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)TargetingController",
              "text" : "TargetingController"
            },
            {
              "kind" : "text",
              "text" : " { "
            },
            {
              "kind" : "keyword",
              "text" : "get"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "keyword",
              "text" : "set"
            },
            {
              "kind" : "text",
              "text" : " }"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/iadvizesdk\/targetingcontroller"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/iadvizesdk\/targetingcontroller"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK": {
  "abstract" : [
    {
      "text" : "The iAdvize SDK lets you provide a unique conversational experience to your users.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "IAdvizeSDK"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "IAdvizeSDK"
    }
  ],
  "role" : "symbol",
  "title" : "IAdvizeSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/iadvizesdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/targetingController": {
  "abstract" : [
    {
      "text" : "An object that allows to configure and monitor the targeting process.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "targetingController"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)TargetingController",
      "text" : "TargetingController"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/targetingController",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "targetingController"
    }
  ],
  "role" : "symbol",
  "title" : "targetingController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/iadvizesdk\/targetingcontroller"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController": {
  "abstract" : [
    {
      "text" : "An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "class"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TargetingController"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TargetingController"
    }
  ],
  "role" : "symbol",
  "title" : "TargetingController",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/targetingcontroller"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Instance Property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "targetingController"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "property"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "targetingController"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "@property"
                },
                {
                  "kind" : "text",
                  "text" : " ("
                },
                {
                  "kind" : "keyword",
                  "text" : "nonatomic"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "strong"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "readonly"
                },
                {
                  "kind" : "text",
                  "text" : ") "
                },
                {
                  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(cs)TargetingController",
                  "text" : "TargetingController"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "identifier",
                  "text" : "targetingController"
                },
                {
                  "kind" : "text",
                  "text" : ";"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title",
        "value" : "IAdvizeSDK"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "IAdvizeSDK"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "IAdvizeSDK"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1targetingController\/title",
        "value" : "targetingController"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1targetingController\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "targetingController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title",
        "value" : "TargetingController"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingController"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TargetingController"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}