{"metadata":{"roleHeading":"Instance Property","title":"transactionController","navigatorTitle":[{"text":"transactionController","kind":"identifier"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK(py)transactionController","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController","text":"TransactionController","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"transactionController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","text":"TransactionController"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/transactionController","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/transactioncontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk\/transactioncontroller"]}],"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"]]},"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/transactionController":{"kind":"symbol","title":"transactionController","navigatorTitle":[{"kind":"identifier","text":"transactionController"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/transactioncontroller","abstract":[{"type":"text","text":"An object that allows to register transactions."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/transactionController","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"transactionController","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController","text":"TransactionController","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"kind":"symbol","title":"IAdvizeSDK","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TransactionController","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller","title":"TransactionController","type":"topic","role":"symbol","navigatorTitle":[{"text":"TransactionController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"transactionController"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"transactionController"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","text":"TransactionController","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"transactionController"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1transactionController\/title","value":"transactionController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1transactionController\/fragments","value":[{"text":"transactionController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","value":"IAdvizeSDK"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","value":[{"kind":"identifier","text":"IAdvizeSDK"}],"op":"replace"},{"value":[{"kind":"identifier","text":"IAdvizeSDK"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/title","value":"TransactionController","op":"replace"},{"value":[{"text":"TransactionController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TransactionController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}