{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"},"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"text":"unique conversational experience","type":"text"}]},{"type":"text","text":" to your users!"}],"metadata":{"role":"collection","modules":[{"name":"IAdvizeConversationSDK"}],"title":"IAdvizeConversationSDK","externalID":"IAdvizeConversationSDK","roleHeading":"Framework","symbolKind":"module"},"primaryContentSections":[{"kind":"content","content":[{"level":2,"anchor":"Overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"Embed the iAdvize Messenger SDK into your app and connect your visitors with your professional agents or ibbü experts through a "},{"type":"strong","inlineContent":[{"text":"fully customized chat experience","type":"text"}]},{"text":". Visitors can ask a question and will receive answers directly on their devices.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[[]]},"topicSections":[{"title":"iAdvize SDK","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger"],"anchor":"iAdvize-SDK"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"],"anchor":"Activation","title":"Activation"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"],"title":"Conversation","anchor":"Conversation"},{"anchor":"Targeting","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum"],"title":"Targeting"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum"],"anchor":"Chatbox-and-Chat-button","title":"Chatbox and Chat button"},{"anchor":"Push-Notifications","title":"Push Notifications","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode"]},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency"],"anchor":"Transactions","title":"Transactions"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData"],"anchor":"Visitor","title":"Visitor"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk"]},{"paths":["\/documentation\/iadvizeconversationsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","title":"IAdvizeSDK","abstract":[{"type":"text","text":"The iAdvize SDK lets you provide a unique conversational experience to your users."}],"role":"symbol","navigatorTitle":[{"text":"IAdvizeSDK","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IAdvizeSDK","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationChannel","kind":"identifier"}],"abstract":[],"title":"ConversationChannel","type":"topic","navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeConversationSDKVersionString":{"abstract":[{"type":"text","text":"Project version string for IAdvizeConversationSDK."}],"fragments":[{"text":"IAdvizeConversationSDKVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeConversationSDKVersionString","title":"IAdvizeConversationSDKVersionString","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizeconversationsdkversionstring"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum":{"navigatorTitle":[{"text":"SDKLanguageOption","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKLanguageOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","kind":"symbol","title":"SDKLanguageOption","abstract":[{"type":"text","text":"Option to specify the language to use for the targeting."}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GraphQLApplicationMode":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLApplicationMode","title":"GraphQLApplicationMode","fragments":[{"kind":"identifier","text":"GraphQLApplicationMode"}],"url":"\/documentation\/iadvizeconversationsdk\/graphqlapplicationmode"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeConversationSDKVersionNumber":{"title":"IAdvizeConversationSDKVersionNumber","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizeconversationsdkversionnumber","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeConversationSDKVersionNumber","abstract":[{"text":"Project version number for IAdvizeConversationSDK.","type":"text"}],"role":"symbol","fragments":[{"text":"IAdvizeConversationSDKVersionNumber","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxControllerDelegate":{"title":"ChatboxControllerDelegate","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontrollerdelegate","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatboxControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate","navigatorTitle":[{"text":"ChatboxControllerDelegate","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OngoingConversation"}],"title":"OngoingConversation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OngoingConversation","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation","url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation","kind":"symbol","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-c.class":{"fragments":[{"kind":"identifier","text":"GDPREnabledOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-c.class","kind":"symbol","title":"GDPREnabledOption","abstract":[],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-c.class","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode":{"navigatorTitle":[{"text":"ApplicationMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Mode for APNS."}],"title":"ApplicationMode","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApplicationMode"}],"url":"\/documentation\/iadvizeconversationsdk\/applicationmode"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IncomingMessageAvatar-swift.enum":{"title":"IncomingMessageAvatar","abstract":[{"type":"text","text":"The image used for the incoming message avatar."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IncomingMessageAvatar","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum","navigatorTitle":[{"text":"IncomingMessageAvatar","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorCustomData":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorCustomData","kind":"symbol","type":"topic","title":"VisitorCustomData","abstract":[],"role":"symbol","fragments":[{"text":"VisitorCustomData","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/visitorcustomdata"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","role":"symbol","abstract":[{"text":"An object that is notified about the targeting process.","type":"text"}],"title":"TargetingControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TargetingControllerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"TargetingControllerDelegate"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-c.class":{"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-c.class","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-c.class","fragments":[{"text":"AuthenticationOption","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AuthenticationOption"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GraphQLCurrency":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLCurrency","url":"\/documentation\/iadvizeconversationsdk\/graphqlcurrency","type":"topic","role":"symbol","abstract":[{"text":"ISO4217 currency code.","type":"text"}],"fragments":[{"kind":"identifier","text":"GraphQLCurrency"}],"title":"GraphQLCurrency"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData":{"url":"\/documentation\/iadvizeconversationsdk\/customdata","abstract":[],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData","navigatorTitle":[{"kind":"identifier","text":"CustomData"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomData","kind":"identifier"}],"title":"CustomData","role":"symbol","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationController","kind":"identifier"}],"title":"ConversationController","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationController"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationOption"}],"abstract":[],"navigatorTitle":[{"text":"NavigationOption","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","title":"NavigationOption","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-c.class":{"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-c.class","title":"ChatboxConfiguration","fragments":[{"text":"ChatboxConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-c.class"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option to authenticate the visitor."}],"role":"symbol","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","title":"AuthenticationOption"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"abstract":[{"text":"The option to configure the GDPR message at the beginning of the conversation.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"kind":"symbol","title":"GDPROption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GDPROption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-c.class":{"title":"SDKLanguageOption","abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-c.class","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-c.class","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"SDKLanguageOption"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"title":"TargetingError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TargetingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","url":"\/documentation\/iadvizeconversationsdk\/targetingerror","abstract":[{"type":"codeVoice","code":"TargetingError"},{"type":"text","text":" is an error that can occur when you try to activate a targeting rule using"},{"type":"text","text":" "},{"code":"TargetingController.activateTargetingRule(targetingRule:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/jwe","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","navigatorTitle":[{"text":"JWE","kind":"identifier"}],"kind":"symbol","title":"JWE","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWE","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TargetingController","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"title":"TargetingController","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingErrorDomain":{"abstract":[],"fragments":[{"text":"TargetingErrorDomain","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingErrorDomain","title":"TargetingErrorDomain","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingerrordomain"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-c.class":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class","title":"NavigationOption","kind":"symbol","role":"symbol","fragments":[{"text":"NavigationOption","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-c.class","abstract":[],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct":{"title":"ChatboxConfiguration","abstract":[{"text":"Encapsulate all the configuration options that can be applied to the chatbox.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatboxConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct","navigatorTitle":[{"text":"ChatboxConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController":{"title":"ChatboxController","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller","abstract":[{"text":"An object that controls the chatbox, which is where the conversation is displayed, and the chat button.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatboxController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","navigatorTitle":[{"text":"ChatboxController","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingrule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","title":"TargetingRule","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TargetingRule","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IncomingMessageAvatar-c.class":{"role":"symbol","abstract":[],"title":"IncomingMessageAvatar","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-c.class","fragments":[{"text":"IncomingMessageAvatar","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-c.class","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"abstract":[{"type":"text","text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPREnabledOption"}],"title":"GDPREnabledOption","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","navigatorTitle":[{"text":"GDPREnabledOption","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-c.class":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-c.class","url":"\/documentation\/iadvizeconversationsdk\/gdproption-c.class","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"GDPROption","fragments":[{"text":"GDPROption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate":{"type":"topic","abstract":[{"type":"text","text":"An object that is notified about the ongoing conversation."}],"title":"ConversationControllerDelegate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationControllerDelegate","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"abstract":[{"type":"text","text":"An object that is notified about visitor interaction with the GDRP message."}],"role":"symbol","navigatorTitle":[{"text":"GDPRDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPRDelegate"}],"url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","title":"GDPRDelegate"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","title":"ActivationStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivationStatus"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/activationstatus","navigatorTitle":[{"text":"ActivationStatus","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"kind":"symbol","abstract":[{"type":"text","text":"Describes a visitor transaction."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Transaction","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Transaction","kind":"identifier"}],"title":"Transaction","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/jweprovider","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider","navigatorTitle":[{"text":"JWEProvider","kind":"identifier"}],"kind":"symbol","title":"JWEProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWEProvider","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/LoggerLogLevel":{"url":"\/documentation\/iadvizeconversationsdk\/loggerloglevel","title":"LoggerLogLevel","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"LoggerLogLevel"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/LoggerLogLevel"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController":{"role":"symbol","navigatorTitle":[{"text":"VisitorController","kind":"identifier"}],"kind":"symbol","title":"VisitorController","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VisitorController"}],"url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-c.class":{"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-c.class","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-c.class","title":"ConversationChannel","type":"topic","fragments":[{"text":"ConversationChannel","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Currency":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Currency"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency","url":"\/documentation\/iadvizeconversationsdk\/currency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Currency","kind":"identifier"}],"title":"Currency","abstract":[{"text":"Currency used in a ","type":"text"},{"type":"codeVoice","code":"Transaction"},{"text":".","type":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GraphQLLanguage":{"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/graphqllanguage","fragments":[{"kind":"identifier","text":"GraphQLLanguage"}],"abstract":[{"type":"text","text":"ISO639-1 language."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLLanguage","title":"GraphQLLanguage"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController":{"title":"TransactionController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionController"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller","navigatorTitle":[{"kind":"identifier","text":"TransactionController"}],"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"type":"topic","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController","navigatorTitle":[{"kind":"identifier","text":"NotificationController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller","title":"NotificationController","role":"symbol","abstract":[{"type":"text","text":"An object that allows to configure push notifications."}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language":{"abstract":[{"text":"ISO639-1 language.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Language","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/language","kind":"symbol","title":"Language","navigatorTitle":[{"kind":"identifier","text":"Language"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Logger":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"title":"Logger","url":"\/documentation\/iadvizeconversationsdk\/logger","abstract":[{"text":"Main structure that is used to log all messages.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"iAdvize-SDK","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"],"title":"iAdvize SDK"},{"title":"Activation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE"],"anchor":"Activation"},{"anchor":"Conversation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"],"title":"Conversation"},{"title":"Targeting","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError"],"anchor":"Targeting"},{"title":"Chatbox and Chat button","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate"],"anchor":"Chatbox-and-Chat-button"},{"anchor":"Push-Notifications","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController"],"title":"Push Notifications"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"],"anchor":"Transactions","title":"Transactions"},{"title":"Visitor","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController"],"anchor":"Visitor"},{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-c.class","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorCustomData"],"title":"Classes","anchor":"Classes"},{"anchor":"Variables","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeConversationSDKVersionNumber","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeConversationSDKVersionString","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingErrorDomain"],"generated":true,"title":"Variables"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLApplicationMode","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLCurrency","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GraphQLLanguage","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/LoggerLogLevel"],"title":"Enumerations","anchor":"Enumerations","generated":true}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","value":"IAdvizeSDK","op":"replace"},{"value":[{"kind":"identifier","text":"IAdvizeSDK"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments"},{"op":"replace","value":[{"text":"IAdvizeSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle"},{"value":"ChatboxControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/fragments","value":[{"kind":"identifier","text":"ChatboxControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"ChatboxControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/title","value":"OngoingConversation"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/fragments","value":[{"text":"OngoingConversation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OngoingConversation"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/title","value":"TargetingControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/fragments","value":[{"kind":"identifier","text":"TargetingControllerDelegate"}]},{"op":"replace","value":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title","value":"ConversationController"},{"value":[{"kind":"identifier","text":"ConversationController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle","op":"replace","value":[{"text":"ConversationController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title","value":"TargetingError"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments","op":"replace","value":[{"text":"TargetingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle","value":[{"text":"TargetingError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title","op":"replace","value":"JWE"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments","value":[{"text":"JWE","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle","value":[{"kind":"identifier","text":"JWE"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title","value":"TargetingController"},{"value":[{"text":"TargetingController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"TargetingController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","op":"replace"},{"value":"ChatboxController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatboxController"}]},{"value":[{"text":"ChatboxController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle"},{"op":"replace","value":"TargetingRule","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","value":[{"text":"TargetingRule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","value":[{"kind":"identifier","text":"TargetingRule"}],"op":"replace"},{"value":"ConversationControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"op":"replace"},{"value":"GDPRDelegate","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}]},{"value":[{"kind":"identifier","text":"GDPRDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title","op":"replace","value":"Transaction"},{"value":[{"text":"Transaction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle","value":[{"text":"Transaction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/title","op":"replace","value":"VisitorController"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/fragments","value":[{"kind":"identifier","text":"VisitorController"}]},{"op":"replace","value":[{"text":"VisitorController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/title","op":"replace","value":"TransactionController"},{"value":[{"text":"TransactionController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TransactionController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/title","value":"NotificationController"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/fragments","value":[{"text":"NotificationController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NotificationController"}]}]}]}