{
  "abstract" : [
    {
      "text" : "Notify the specified delegate.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
        "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum\/delegate(delegate:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:22IAdvizeConversationSDK17GDPREnabledOptionO8delegateyAcA12GDPRDelegate_p_tcACmF",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "case"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "delegate"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "externalParam",
        "text" : "delegate"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(pl)GDPRDelegate",
        "text" : "GDPRDelegate"
      },
      {
        "kind" : "text",
        "text" : ")"
      }
    ],
    "modules" : [
      {
        "name" : "IAdvizeConversationSDK"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Case",
    "symbolKind" : "case",
    "title" : "GDPREnabledOption.delegate(delegate:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "case"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "delegate"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "delegate"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(pl)GDPRDelegate",
              "text" : "GDPRDelegate"
            },
            {
              "kind" : "text",
              "text" : ")"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "You can use this option to open a dedicated screen in your app.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum\/delegate(delegate:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK": {
  "abstract" : [
    {
      "text" : "Take your app to the next level and provide a ",
      "type" : "text"
    },
    {
      "inlineContent" : [
        {
          "text" : "unique conversational experience",
          "type" : "text"
        }
      ],
      "type" : "strong"
    },
    {
      "text" : " to your users!",
      "type" : "text"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "IAdvizeConversationSDK",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate": {
  "abstract" : [
    {
      "text" : "An object that is notified about visitor interaction with the GDRP message.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "protocol"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "GDPRDelegate"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "GDPRDelegate"
    }
  ],
  "role" : "symbol",
  "title" : "GDPRDelegate",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/gdprdelegate"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum": {
  "abstract" : [
    {
      "text" : "The option to configure the behavior when the visitor touches the “More information” button in the GDPR message.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "GDPREnabledOption"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "GDPREnabledOption"
    }
  ],
  "role" : "symbol",
  "title" : "GDPREnabledOption",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum"
},
"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum/delegate(delegate:)": {
  "abstract" : [
    {
      "text" : "Notify the specified delegate.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "delegate"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "delegate"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@M@IAdvizeConversationSDK@objc(pl)GDPRDelegate",
      "text" : "GDPRDelegate"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum\/delegate(delegate:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "GDPREnabledOption.delegate(delegate:)",
  "type" : "topic",
  "url" : "\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum\/delegate(delegate:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title",
        "value" : "GDPRDelegate"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "GDPRDelegate"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "GDPRDelegate"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}