{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError\/sdkNotActivated"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotActivated","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingErrorSdkNotActivated","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@IAdvizeConversationSDK@E@TargetingError@TargetingErrorSdkNotActivated","roleHeading":"Case","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"title":"TargetingError.sdkNotActivated"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sdkNotActivated","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"The iAdvize SDK is not activated. Call "},{"code":"activate(projectId:authenticationOption:gdprOption:completion:)","type":"codeVoice"},{"type":"text","text":" first."}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingerror\/sdknotactivated"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingerror\/sdknotactivated"]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"title":"TargetingError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TargetingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","url":"\/documentation\/iadvizeconversationsdk\/targetingerror","abstract":[{"type":"codeVoice","code":"TargetingError"},{"type":"text","text":" is an error that can occur when you try to activate a targeting rule using"},{"type":"text","text":" "},{"code":"TargetingController.activateTargetingRule(targetingRule:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError/sdkNotActivated":{"type":"topic","title":"TargetingError.sdkNotActivated","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"sdkNotActivated","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingErrorSdkNotActivated","kind":"identifier"}],"abstract":[{"type":"text","text":"The iAdvize SDK is not activated. Call "},{"type":"codeVoice","code":"activate(projectId:authenticationOption:gdprOption:completion:)"},{"type":"text","text":" first."}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingerror\/sdknotactivated","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError\/sdkNotActivated"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"TargetingErrorSdkNotActivated","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"TargetingErrorSdkNotActivated","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"TargetingErrorSdkNotActivated","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title","op":"replace","value":"TargetingError"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments","value":[{"text":"TargetingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle","value":[{"text":"TargetingError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError~1sdkNotActivated\/title","value":"TargetingErrorSdkNotActivated"},{"op":"replace","value":[{"text":"TargetingErrorSdkNotActivated","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError~1sdkNotActivated\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}