{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerTransaction","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"transaction"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","kind":"typeIdentifier","text":"Transaction","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)Transaction"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"transaction","content":[{"type":"paragraph","inlineContent":[{"text":"The transaction to register.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/transactioncontroller\/registertransaction(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/transactioncontroller\/registertransaction(_:)"]}],"abstract":[{"type":"text","text":"Register a new transaction concluded by your visitor."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/registerTransaction(_:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"registerTransaction:"}],"title":"registerTransaction(_:)","externalID":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController(im)registerTransaction:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerTransaction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)Transaction","text":"Transaction"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"IAdvizeConversationSDK"}],"role":"symbol","symbolKind":"method"},"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TransactionController","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller","title":"TransactionController","type":"topic","role":"symbol","navigatorTitle":[{"text":"TransactionController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"title":"Transaction","navigatorTitle":[{"text":"Transaction","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","type":"topic","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Transaction"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController/registerTransaction(_:)":{"abstract":[{"type":"text","text":"Register a new transaction concluded by your visitor."}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller\/registertransaction(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerTransaction:"}],"title":"registerTransaction(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerTransaction"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)Transaction","text":"Transaction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/registerTransaction(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"registerTransaction:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerTransaction:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"registerTransaction:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","kind":"typeIdentifier","text":"Transaction","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)Transaction"},{"text":" *) ","kind":"text"},{"text":"transaction","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The transaction to register.","type":"text"}],"type":"paragraph"}],"name":"transaction"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/title","op":"replace","value":"TransactionController"},{"op":"replace","value":[{"text":"TransactionController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/navigatorTitle","value":[{"kind":"identifier","text":"TransactionController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title","value":"Transaction"},{"op":"replace","value":[{"kind":"identifier","text":"Transaction"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments"},{"value":[{"text":"Transaction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle"},{"value":"registerTransaction:","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController~1registerTransaction(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerTransaction:"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController~1registerTransaction(_:)\/fragments","op":"replace"}]}]}