{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController\/setupChatboxWithConfiguration:"},"metadata":{"role":"symbol","title":"setupChatboxWithConfiguration:","roleHeading":"Instance Method","navigatorTitle":[{"text":"setupChatboxWithConfiguration:","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"method","externalID":"c:@CM@IAdvizeConversationSDK@objc(cs)ChatboxController(im)setupChatboxWithConfiguration:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setupChatboxWithConfiguration:"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/setupchatboxwithconfiguration:"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setupChatboxWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ChatboxConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-c.class","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ChatboxConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController"]]},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController":{"abstract":[{"text":"An object that controls the chatbox, which is where the conversation is displayed, and the chat button.","type":"text"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatboxController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","title":"ChatboxController","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatboxController"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController/setupChatboxWithConfiguration:":{"navigatorTitle":[{"text":"setupChatboxWithConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController\/setupChatboxWithConfiguration:","abstract":[],"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"setupChatboxWithConfiguration:","kind":"identifier"}],"kind":"symbol","title":"setupChatboxWithConfiguration:","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller\/setupchatboxwithconfiguration:","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-c.class":{"abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-c.class","role":"symbol","fragments":[{"text":"ChatboxConfiguration","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-c.class","kind":"symbol","type":"topic","title":"ChatboxConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ChatboxController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments","value":[{"text":"ChatboxController","kind":"identifier"}]},{"op":"replace","value":[{"text":"ChatboxController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle"}]}]}