{"sections":[],"abstract":[{"text":"The option to authenticate the visitor.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/==(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"},{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/anonymous","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/secured(jweProvider:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/simple(userId:)"]},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/Equatable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/SQ"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationOption","kind":"identifier"}],"languages":["swift"]}]}],"seeAlsoSections":[{"generated":true,"title":"Activation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"],"anchor":"Activation"}],"metadata":{"roleHeading":"Enumeration","externalID":"s:22IAdvizeConversationSDK20AuthenticationOptionO","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AuthenticationOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationOption"}],"symbolKind":"enum","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"title":"AuthenticationOption"},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","interfaceLanguage":"swift"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum/simple(userId:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/simple(userId:)","abstract":[{"text":"Simple authentication using a unique identifier.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"simple"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum\/simple(userid:)","title":"AuthenticationOption.simple(userId:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationOption","kind":"identifier"}],"abstract":[{"type":"text","text":"The option to authenticate the visitor."}],"role":"symbol","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","title":"AuthenticationOption"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum/Equatable-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum\/equatable-implementations","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/Equatable-Implementations"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"abstract":[{"type":"text","text":"An object that is notified about visitor interaction with the GDRP message."}],"role":"symbol","navigatorTitle":[{"text":"GDPRDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPRDelegate"}],"url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","title":"GDPRDelegate"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/jwe","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","navigatorTitle":[{"text":"JWE","kind":"identifier"}],"kind":"symbol","title":"JWE","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWE","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","title":"ActivationStatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActivationStatus"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/activationstatus","navigatorTitle":[{"text":"ActivationStatus","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum/==(_:_:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/==(_:_:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"=="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK20AuthenticationOptionO","kind":"typeIdentifier","text":"AuthenticationOption"},{"kind":"text","text":", "},{"text":"AuthenticationOption","preciseIdentifier":"s:22IAdvizeConversationSDK20AuthenticationOptionO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum\/==(_:_:)","title":"==(_:_:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/jweprovider","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider","navigatorTitle":[{"text":"JWEProvider","kind":"identifier"}],"kind":"symbol","title":"JWEProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWEProvider","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","title":"Swift.Equatable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"abstract":[{"type":"text","text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPREnabledOption"}],"title":"GDPREnabledOption","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","navigatorTitle":[{"text":"GDPREnabledOption","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"abstract":[{"text":"The option to configure the GDPR message at the beginning of the conversation.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","role":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"kind":"symbol","title":"GDPROption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GDPROption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum/secured(jweProvider:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/secured(jweProvider:)","abstract":[{"type":"text","text":"Secured authentication using a JWE (encrypted JWT)."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secured"},{"kind":"text","text":"("},{"text":"jweProvider","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK11JWEProviderP","text":"JWEProvider"},{"kind":"text","text":")"}],"url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum\/secured(jweprovider:)","title":"AuthenticationOption.secured(jweProvider:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum/anonymous":{"abstract":[{"type":"text","text":"Anonymous authentication."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"anonymous","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AuthenticationOption.anonymous","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum\/anonymous","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum\/anonymous"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"GDPRDelegate","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"GDPRDelegate"}],"op":"replace"},{"value":"JWE","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments","value":[{"text":"JWE","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"JWE","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle"}]}]}