{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","doc:\/\/com.iadvize.conversation.sdk\/SE","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH","doc:\/\/com.iadvize.conversation.sdk\/SY","doc:\/\/com.iadvize.conversation.sdk\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum"]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationChannel"}],"role":"symbol","navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"symbolKind":"enum","title":"ConversationChannel","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"s:22IAdvizeConversationSDK0B7ChannelO","roleHeading":"Enumeration"},"sections":[],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/chat","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/video"],"anchor":"Enumeration-Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/Equatable-Implementations","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"seeAlsoSections":[{"title":"Targeting","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum"],"anchor":"Targeting"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationChannel"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingerror","type":"topic","abstract":[{"code":"TargetingError","type":"codeVoice"},{"type":"text","text":" is an error that can occur when you try to activate a targeting rule using"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TargetingController.activateTargetingRule(targetingRule:)"},{"text":".","type":"text"}],"title":"TargetingError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TargetingError","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum/chat":{"kind":"symbol","abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum\/chat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/chat","role":"symbol","type":"topic","title":"ConversationChannel.chat"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","navigatorTitle":[{"kind":"identifier","text":"NavigationOption"}],"title":"NavigationOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"NavigationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum":{"url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum","abstract":[{"type":"text","text":"Option to specify the language to use for the targeting."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","navigatorTitle":[{"text":"SDKLanguageOption","kind":"identifier"}],"title":"SDKLanguageOption","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDKLanguageOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"title":"TargetingController","role":"symbol","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"type":"topic","navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingController"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum/RawRepresentable-Implementations":{"type":"topic","kind":"article","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/RawRepresentable-Implementations","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum\/rawrepresentable-implementations"},"doc://com.iadvize.conversation.sdk/s8CopyableP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.iadvize.conversation.sdk/s8SendableP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum/video":{"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum\/video","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/video","title":"ConversationChannel.video","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"video"}],"abstract":[]},"doc://com.iadvize.conversation.sdk/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SY","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","title":"ConversationChannel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationChannel","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language":{"navigatorTitle":[{"kind":"identifier","text":"Language"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Language"}],"abstract":[{"text":"ISO639-1 language.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","title":"Language","kind":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/language"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","type":"topic","navigatorTitle":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"title":"TargetingControllerDelegate","url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingControllerDelegate"}],"abstract":[{"type":"text","text":"An object that is notified about the targeting process."}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SE","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","url":"\/documentation\/iadvizeconversationsdk\/targetingrule","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"abstract":[],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum/init(rawValue:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/init(rawValue:)","abstract":[],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum/Equatable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum\/Equatable-Implementations","title":"Equatable Implementations","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title","value":"TargetingError"},{"value":[{"text":"TargetingError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle","value":[{"text":"TargetingError","kind":"identifier"}]},{"value":"TargetingController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","value":[{"text":"TargetingController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","value":[{"text":"TargetingController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/title","value":"TargetingControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/fragments","value":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/navigatorTitle"},{"value":"TargetingRule","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","op":"replace"},{"value":[{"kind":"identifier","text":"TargetingRule"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","value":[{"text":"TargetingRule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}