{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationControllerDelegate"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/conversationController(_:shouldOpen:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/didReceiveNewMessage(content:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/ongoingConversationUpdated(ongoingConversation:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationControllerDelegate","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"roleHeading":"Protocol","title":"ConversationControllerDelegate","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(pl)ConversationControllerDelegate"},"abstract":[{"text":"An object that is notified about the ongoing conversation.","type":"text"}],"seeAlsoSections":[{"generated":true,"title":"Conversation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"],"anchor":"Conversation"}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate"]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationController":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontroller","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","type":"topic","role":"symbol","title":"ConversationController","navigatorTitle":[{"text":"ConversationController","kind":"identifier"}],"abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationController","kind":"identifier"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/OngoingConversation":{"role":"symbol","title":"OngoingConversation","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OngoingConversation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"OngoingConversation","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/ongoingconversation","abstract":[],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate/didReceiveNewMessage(content:)":{"abstract":[{"text":"Called when a new incoming message has been received.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveNewMessage"},{"text":"(","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol","title":"didReceiveNewMessage(content:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/didReceiveNewMessage(content:)","navigatorTitle":[{"kind":"identifier","text":"didReceiveNewMessageWithContent:"}],"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate\/didreceivenewmessage(content:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate":{"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationControllerDelegate"}],"abstract":[{"text":"An object that is notified about the ongoing conversation.","type":"text"}],"title":"ConversationControllerDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConversationControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate/conversationController(_:shouldOpen:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"ConversationController","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController"},{"text":", ","kind":"text"},{"text":"shouldOpen","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"conversationController:shouldOpen:"}],"required":true,"abstract":[{"text":"Called on the delegate when the user has tapped on a link to ask whether the URL should be opened.","type":"text"}],"title":"conversationController(_:shouldOpen:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/conversationController(_:shouldOpen:)","url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate\/conversationcontroller(_:shouldopen:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationControllerDelegate/ongoingConversationUpdated(ongoingConversation:)":{"required":true,"url":"\/documentation\/iadvizeconversationsdk\/conversationcontrollerdelegate\/ongoingconversationupdated(ongoingconversation:)","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/ongoingConversationUpdated(ongoingConversation:)","navigatorTitle":[{"text":"ongoingConversationUpdatedWithOngoingConversation:","kind":"identifier"}],"title":"ongoingConversationUpdated(ongoingConversation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ongoingConversationUpdated","kind":"identifier"},{"kind":"text","text":"("},{"text":"ongoingConversation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OngoingConversation","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)OngoingConversation"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Called each time a visitor is entering in a new or existing ongoing conversation.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ConversationControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationControllerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/conversationController(_:shouldOpen:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/didReceiveNewMessage(content:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationControllerDelegate\/ongoingConversationUpdated(ongoingConversation:)"]}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/OngoingConversation"],"title":"Conversation","anchor":"Conversation","generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationControllerDelegate","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ConversationController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/fragments","value":[{"text":"ConversationController","kind":"identifier"}]},{"value":[{"text":"ConversationController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/title","value":"OngoingConversation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/fragments","value":[{"kind":"identifier","text":"OngoingConversation"}]},{"value":[{"text":"OngoingConversation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1OngoingConversation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1didReceiveNewMessage(content:)\/title","value":"didReceiveNewMessageWithContent:","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1didReceiveNewMessage(content:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didReceiveNewMessageWithContent:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/title","op":"replace","value":"ConversationControllerDelegate"},{"value":[{"text":"ConversationControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/fragments"},{"value":[{"text":"ConversationControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1conversationController(_:shouldOpen:)\/title","op":"replace","value":"conversationController:shouldOpen:"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1conversationController(_:shouldOpen:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"conversationController:shouldOpen:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1ongoingConversationUpdated(ongoingConversation:)\/title","value":"ongoingConversationUpdatedWithOngoingConversation:"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ConversationControllerDelegate~1ongoingConversationUpdated(ongoingConversation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"ongoingConversationUpdatedWithOngoingConversation:","kind":"identifier"}]}]}]}