{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CustomData","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"sections":[],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataBoolean(_:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataDouble(_:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataInt(_:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataString(_:)"]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData","interfaceLanguage":"swift"},"metadata":{"title":"CustomData","roleHeading":"Enumeration","externalID":"s:22IAdvizeConversationSDK10CustomDataO","role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomData"}],"navigatorTitle":[{"text":"CustomData","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController"],"anchor":"Visitor","title":"Visitor"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/customdata"]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData/customDataBoolean(_:)":{"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/customdata\/customdataboolean(_:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataBoolean(_:)","title":"CustomData.customDataBoolean(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"customDataBoolean","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"abstract":[],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData/customDataDouble(_:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customDataDouble","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataDouble(_:)","type":"topic","title":"CustomData.customDataDouble(_:)","url":"\/documentation\/iadvizeconversationsdk\/customdata\/customdatadouble(_:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData/customDataString(_:)":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"customDataString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"CustomData.customDataString(_:)","url":"\/documentation\/iadvizeconversationsdk\/customdata\/customdatastring(_:)","type":"topic","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataString(_:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VisitorController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitorController","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller","role":"symbol","kind":"symbol","title":"VisitorController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData":{"title":"CustomData","abstract":[],"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomData"}],"url":"\/documentation\/iadvizeconversationsdk\/customdata","kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData/customDataInt(_:)":{"url":"\/documentation\/iadvizeconversationsdk\/customdata\/customdataint(_:)","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData\/customDataInt(_:)","title":"CustomData.customDataInt(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customDataInt","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/title","value":"VisitorController","op":"replace"},{"value":[{"text":"VisitorController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/navigatorTitle","value":[{"kind":"identifier","text":"VisitorController"}],"op":"replace"}]}]}