{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum\/disabled","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum\/enabled(option:)"],"anchor":"Enumeration-Cases","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Enumeration","title":"GDPROption","navigatorTitle":[{"kind":"identifier","text":"GDPROption"}],"role":"symbol","symbolKind":"enum","externalID":"s:22IAdvizeConversationSDK10GDPROptionO","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"modules":[{"name":"IAdvizeConversationSDK"}]},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"seeAlsoSections":[{"title":"Activation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"],"generated":true,"anchor":"Activation"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum/enabled(option:)":{"url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum\/enabled(option:)","title":"GDPROption.enabled(option:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"enabled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"option"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK17GDPREnabledOptionO","text":"GDPREnabledOption","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum\/enabled(option:)","role":"symbol","abstract":[{"type":"text","text":"The GDPR message is displayed at the beginning of the conversation."}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GDPRDelegate","kind":"identifier"}],"title":"GDPRDelegate","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","abstract":[{"type":"text","text":"An object that is notified about visitor interaction with the GDRP message."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPRDelegate"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPREnabledOption"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message."}],"title":"GDPREnabledOption","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GDPREnabledOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationOption"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The option to authenticate the visitor."}],"title":"AuthenticationOption","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","role":"symbol","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"kind":"symbol","type":"topic","title":"GDPROption","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"role":"symbol","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"kind":"symbol","title":"JWE","url":"\/documentation\/iadvizeconversationsdk\/jwe","abstract":[],"role":"symbol","navigatorTitle":[{"text":"JWE","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWE"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationStatus","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/activationstatus","title":"ActivationStatus","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ActivationStatus","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWEProvider"}],"type":"topic","kind":"symbol","title":"JWEProvider","url":"\/documentation\/iadvizeconversationsdk\/jweprovider","abstract":[],"role":"symbol","navigatorTitle":[{"text":"JWEProvider","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum/disabled":{"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum\/disabled","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum\/disabled","type":"topic","abstract":[{"type":"text","text":"The GDPR message is not displayed at the beginning of the conversation."}],"title":"GDPROption.disabled","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"GDPRDelegate","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}]},{"op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle"},{"value":"JWE","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JWE"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle","op":"replace","value":[{"text":"JWE","kind":"identifier"}]}]}]}