{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"abstract":[{"type":"text","text":"An object that is notified about visitor interaction with the GDRP message."}],"sections":[],"seeAlsoSections":[{"title":"Activation","anchor":"Activation","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"],"generated":true}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GDPRDelegate","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"GDPRDelegate","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:@M@IAdvizeConversationSDK@objc(pl)GDPRDelegate","title":"GDPRDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPRDelegate"}]},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate\/didTapMoreInformation()"],"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/gdprdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/gdprdelegate"]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/AuthenticationOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationOption"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The option to authenticate the visitor."}],"title":"AuthenticationOption","url":"\/documentation\/iadvizeconversationsdk\/authenticationoption-swift.enum","role":"symbol","navigatorTitle":[{"text":"AuthenticationOption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/AuthenticationOption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate/didTapMoreInformation()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapMoreInformation"},{"kind":"text","text":"()"}],"required":true,"kind":"symbol","type":"topic","title":"didTapMoreInformation()","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate\/didtapmoreinformation()","abstract":[{"text":"Called when the visitor tap on ‘More information’ in the GDPR message.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"didTapMoreInformation","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate\/didTapMoreInformation()"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ActivationStatus":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ActivationStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationStatus","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/activationstatus","title":"ActivationStatus","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ActivationStatus","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPREnabledOption-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPREnabledOption"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The option to configure the behavior when the visitor touches the “More information” button in the GDPR message."}],"title":"GDPREnabledOption","url":"\/documentation\/iadvizeconversationsdk\/gdprenabledoption-swift.enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GDPREnabledOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPREnabledOption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPRDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GDPRDelegate","kind":"identifier"}],"title":"GDPRDelegate","url":"\/documentation\/iadvizeconversationsdk\/gdprdelegate","abstract":[{"type":"text","text":"An object that is notified about visitor interaction with the GDRP message."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GDPRDelegate"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/GDPROption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GDPROption"}],"kind":"symbol","type":"topic","title":"GDPROption","url":"\/documentation\/iadvizeconversationsdk\/gdproption-swift.enum","abstract":[{"type":"text","text":"The option to configure the GDPR message at the beginning of the conversation."}],"role":"symbol","navigatorTitle":[{"text":"GDPROption","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPROption-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWEProvider":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWEProvider"}],"type":"topic","kind":"symbol","title":"JWEProvider","url":"\/documentation\/iadvizeconversationsdk\/jweprovider","abstract":[],"role":"symbol","navigatorTitle":[{"text":"JWEProvider","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWEProvider"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/JWE":{"kind":"symbol","title":"JWE","url":"\/documentation\/iadvizeconversationsdk\/jwe","abstract":[],"role":"symbol","navigatorTitle":[{"text":"JWE","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWE"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"GDPRDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GDPRDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GDPRDelegate","kind":"identifier"}]},{"value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/GDPRDelegate\/didTapMoreInformation()"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Activation","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/JWE"],"anchor":"Activation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"GDPRDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"didTapMoreInformation","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate~1didTapMoreInformation()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate~1didTapMoreInformation()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didTapMoreInformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/title","value":"GDPRDelegate"},{"value":[{"kind":"identifier","text":"GDPRDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/fragments"},{"value":[{"kind":"identifier","text":"GDPRDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1GDPRDelegate\/navigatorTitle"},{"value":"JWE","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/fragments","value":[{"text":"JWE","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1JWE\/navigatorTitle","value":[{"kind":"identifier","text":"JWE"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}