{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"metadata":{"navigatorTitle":[{"text":"IAdvizeSDK","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"title":"IAdvizeSDK","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IAdvizeSDK","kind":"identifier"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK","roleHeading":"Class"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"]}],"abstract":[{"type":"text","text":"The iAdvize SDK lets you provide a unique conversational experience to your users."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger"],"title":"iAdvize SDK","anchor":"iAdvize-SDK","generated":true}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/iadvizesdk"]}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAdvizeSDK","kind":"identifier"}]}]},{"content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You access the SDK through the "},{"type":"codeVoice","code":"shared"},{"type":"text","text":" instance."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Start by activating the SDK using "},{"type":"codeVoice","code":"activate(projectId:authenticationOption:gdprOption:completion:)"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"text","text":"You can then rely on the provided controllers to configure and monitor the various parts of the conversational"},{"text":" ","type":"text"},{"type":"text","text":"experience:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"targetingController","type":"codeVoice"},{"type":"text","text":" lets you control the targeting process."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"chatboxController","type":"codeVoice"},{"type":"text","text":" lets you to configure the chatbox and the chat button."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"notificationController"},{"text":" lets you configure push notifications.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"conversationController"},{"type":"text","text":" lets you monitor the ongoing conversation."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"transactionController"},{"type":"text","text":" lets you register transactions."}]}]}],"type":"unorderedList"}],"kind":"content"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activationStatus","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/chatboxController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/conversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logLevel","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/notificationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/targetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/transactionController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/visitorController"],"anchor":"Instance-Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activate(projectId:authenticationOption:gdprOption:completion:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/debugInfo()","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logout(completion:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/shared"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/conversationController":{"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/conversationcontroller","abstract":[{"text":"An object that allows to monitor the conversation.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"conversationController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationController","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ConversationController"}],"navigatorTitle":[{"text":"conversationController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/conversationController","title":"conversationController","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/logout(completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/logout(completion:)","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logout(completion:)","abstract":[{"type":"text","text":"Logout the visitor from the iAdvize SDK."}],"navigatorTitle":[{"text":"logoutWithCompletion:","kind":"identifier"}],"title":"logout(completion:)"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/logLevel":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Logger","preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO"},{"kind":"text","text":"."},{"preciseIdentifier":"s:22IAdvizeConversationSDK6LoggerO8LogLevelO","text":"LogLevel","kind":"typeIdentifier"}],"kind":"symbol","title":"logLevel","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/loglevel","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logLevel","abstract":[{"type":"text","text":"The log level of the iAdvize SDK console logger."}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/chatboxController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/chatboxController","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatboxController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)ChatboxController","text":"ChatboxController","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"An object that controls the chatbox and the chat button.","type":"text"}],"title":"chatboxController","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/chatboxcontroller","navigatorTitle":[{"kind":"identifier","text":"chatboxController"}],"type":"topic","kind":"symbol"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/transactionController":{"navigatorTitle":[{"text":"transactionController","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An object that allows to register transactions."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/transactionController","role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/transactioncontroller","title":"transactionController","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TransactionController","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController"}]},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/debugInfo()":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/debugInfo()","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/debuginfo()","kind":"symbol","title":"debugInfo()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"debugInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"debugInfo","kind":"identifier"}],"abstract":[{"text":"Returns a JSON ","type":"text"},{"type":"codeVoice","code":"String"},{"type":"text","text":" containing detailed information about the current state of the iAdvize SDK."}],"role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/activationStatus":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activationStatus","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ActivationStatus","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK16ActivationStatusO"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activationstatus","title":"activationStatus"},"doc://com.iadvize.conversation.sdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ","title":"Swift.Equatable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/setLogLevel:":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/setLogLevel:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setLogLevel:"}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/setloglevel:","title":"setLogLevel:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"setLogLevel:"}],"type":"topic","kind":"symbol"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Logger":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/logger","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger","title":"Logger","abstract":[{"type":"text","text":"Main structure that is used to log all messages."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/activate(projectId:authenticationOption:gdprOption:completion:)":{"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activate(projectid:authenticationoption:gdproption:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"projectId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"authenticationOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AuthenticationOption","kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK20AuthenticationOptionO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"gdprOption"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK10GDPROptionO","text":"GDPROption","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"success","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activate(projectId:authenticationOption:gdprOption:completion:)","role":"symbol","type":"topic","title":"activate(projectId:authenticationOption:gdprOption:completion:)","abstract":[{"text":"Activate the iAdvize SDK for the visitor.","type":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/visitorController":{"abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/visitorController","navigatorTitle":[{"text":"visitorController","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"visitorController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VisitorController","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)VisitorController","kind":"typeIdentifier"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/visitorcontroller","kind":"symbol","type":"topic","title":"visitorController"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/notificationController":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notificationController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NotificationController","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)NotificationController"}],"navigatorTitle":[{"kind":"identifier","text":"notificationController"}],"kind":"symbol","abstract":[{"text":"An object that allows to configure the push notifications.","type":"text"}],"title":"notificationController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/notificationController","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/notificationcontroller"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/getLogLevel":{"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/getloglevel","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"getLogLevel","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"getLogLevel","kind":"identifier"}],"kind":"symbol","title":"getLogLevel","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/getLogLevel"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/init":{"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","title":"init","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/activateWithProjectId:authenticationOption:gdprOption:completion:":{"title":"activateWithProjectId:authenticationOption:gdprOption:completion:","abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activateWithProjectId:authenticationOption:gdprOption:completion:","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"activateWithProjectId:authenticationOption:gdprOption:completion:"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/activatewithprojectid:authenticationoption:gdproption:completion:","navigatorTitle":[{"text":"activateWithProjectId:authenticationOption:gdprOption:completion:","kind":"identifier"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/shared":{"kind":"symbol","title":"shared","abstract":[{"type":"text","text":"The shared "},{"type":"codeVoice","code":"IAdvizeSDK"},{"type":"text","text":" instance."}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/shared","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IAdvizeSDK","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/shared"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAdvizeSDK","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","title":"IAdvizeSDK","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK/targetingController":{"abstract":[{"text":"An object that allows to configure and monitor the targeting process.","type":"text"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk\/targetingcontroller","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetingController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingController","kind":"typeIdentifier","text":"TargetingController"}],"title":"targetingController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/targetingController","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"targetingController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"IAdvizeSDK","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"IAdvizeSDK","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"IAdvizeSDK","kind":"identifier"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/chatboxController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/conversationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/notificationController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/targetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/transactionController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/visitorController"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/activateWithProjectId:authenticationOption:gdprOption:completion:","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/debugInfo()","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/getLogLevel","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/init","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/logout(completion:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/setLogLevel:"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK\/shared"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAdvizeSDK","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"conversationController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1conversationController\/title"},{"value":[{"kind":"identifier","text":"conversationController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1conversationController\/fragments"},{"value":"logoutWithCompletion:","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1logout(completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"logoutWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1logout(completion:)\/fragments"},{"value":"chatboxController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1chatboxController\/title"},{"value":[{"text":"chatboxController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1chatboxController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1transactionController\/title","value":"transactionController","op":"replace"},{"value":[{"kind":"identifier","text":"transactionController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1transactionController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1debugInfo()\/title","value":"debugInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1debugInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"debugInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1visitorController\/title","value":"visitorController"},{"value":[{"kind":"identifier","text":"visitorController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1visitorController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1notificationController\/title","op":"replace","value":"notificationController"},{"value":[{"text":"notificationController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1notificationController\/fragments"},{"value":"shared","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1shared\/title"},{"value":[{"kind":"identifier","text":"shared"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1shared\/fragments"},{"value":"IAdvizeSDK","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","op":"replace","value":[{"kind":"identifier","text":"IAdvizeSDK"}]},{"op":"replace","value":[{"kind":"identifier","text":"IAdvizeSDK"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle"},{"op":"replace","value":"targetingController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1targetingController\/title"},{"value":[{"kind":"identifier","text":"targetingController"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK~1targetingController\/fragments","op":"replace"}]}]}