{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"kind":"symbol","metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"title":"IncomingMessageAvatar","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"IncomingMessageAvatar","kind":"identifier"}],"role":"symbol","externalID":"s:22IAdvizeConversationSDK21IncomingMessageAvatarO","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"IncomingMessageAvatar","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The image used for the incoming message avatar."}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum\/image(image:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum\/url(url:)"],"title":"Enumeration Cases"}],"seeAlsoSections":[{"title":"Chatbox and Chat button","anchor":"Chatbox-and-Chat-button","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IncomingMessageAvatar","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IncomingMessageAvatar-swift.enum/image(image:)":{"url":"\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-swift.enum\/image(image:)","role":"symbol","title":"IncomingMessageAvatar.image(image:)","abstract":[{"type":"text","text":"A local image."}],"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum\/image(image:)","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxController":{"abstract":[{"text":"An object that controls the chatbox, which is where the conversation is displayed, and the chat button.","type":"text"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatboxController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxController","title":"ChatboxController","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatboxController"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxConfiguration-swift.struct":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxConfiguration-swift.struct","abstract":[{"text":"Encapsulate all the configuration options that can be applied to the chatbox.","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/chatboxconfiguration-swift.struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatboxConfiguration"}],"navigatorTitle":[{"text":"ChatboxConfiguration","kind":"identifier"}],"type":"topic","title":"ChatboxConfiguration","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ChatboxControllerDelegate":{"title":"ChatboxControllerDelegate","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ChatboxControllerDelegate","abstract":[],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/chatboxcontrollerdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatboxControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ChatboxControllerDelegate","kind":"identifier"}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IncomingMessageAvatar-swift.enum/url(url:)":{"title":"IncomingMessageAvatar.url(url:)","abstract":[{"type":"text","text":"A remote image at the specified URL."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum\/url(url:)","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"url":"\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-swift.enum\/url(url:)","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IncomingMessageAvatar-swift.enum":{"title":"IncomingMessageAvatar","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IncomingMessageAvatar-swift.enum","abstract":[{"type":"text","text":"The image used for the incoming message avatar."}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/incomingmessageavatar-swift.enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IncomingMessageAvatar","kind":"identifier"}],"navigatorTitle":[{"text":"IncomingMessageAvatar","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"ChatboxController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/fragments","value":[{"kind":"identifier","text":"ChatboxController"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ChatboxController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/title","value":"ChatboxControllerDelegate"},{"op":"replace","value":[{"kind":"identifier","text":"ChatboxControllerDelegate"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1ChatboxControllerDelegate\/navigatorTitle","value":[{"text":"ChatboxControllerDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}