{"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger","interfaceLanguage":"swift"},"metadata":{"externalID":"s:22IAdvizeConversationSDK6LoggerO","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"role":"symbol","title":"Logger","modules":[{"name":"IAdvizeConversationSDK"}],"symbolKind":"enum"},"topicSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger\/LogLevel"],"title":"Enumerations","generated":true,"anchor":"Enumerations"}],"seeAlsoSections":[{"generated":true,"anchor":"iAdvize-SDK","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK"],"title":"iAdvize SDK"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/logger"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"abstract":[{"text":"Main structure that is used to log all messages.","type":"text"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Logger":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/logger","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger","title":"Logger","abstract":[{"type":"text","text":"Main structure that is used to log all messages."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Logger/LogLevel":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/logger\/loglevel","abstract":[{"text":"Level of a logged message.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Logger\/LogLevel","title":"Logger.LogLevel"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/IAdvizeSDK":{"type":"topic","kind":"symbol","abstract":[{"text":"The iAdvize SDK lets you provide a unique conversational experience to your users.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IAdvizeSDK","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IAdvizeSDK"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/IAdvizeSDK","title":"IAdvizeSDK","url":"\/documentation\/iadvizeconversationsdk\/iadvizesdk","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/title","value":"IAdvizeSDK"},{"value":[{"kind":"identifier","text":"IAdvizeSDK"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/fragments","op":"replace"},{"value":[{"text":"IAdvizeSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1IAdvizeSDK\/navigatorTitle","op":"replace"}]}]}