{"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum"]}],"metadata":{"roleHeading":"Enumeration","externalID":"s:22IAdvizeConversationSDK16NavigationOptionO","role":"symbol","title":"NavigationOption","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NavigationOption","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"navigatorTitle":[{"text":"NavigationOption","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NavigationOption","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","seeAlsoSections":[{"title":"Targeting","generated":true,"anchor":"Targeting","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"]}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/activateNewRule(targetingRule:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/clearActiveRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/keepActiveRule"],"generated":true}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TargetingController","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"title":"TargetingController","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","role":"symbol","abstract":[{"text":"An object that is notified about the targeting process.","type":"text"}],"title":"TargetingControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TargetingControllerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"TargetingControllerDelegate"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum/keepActiveRule":{"abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/keepActiveRule","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keepActiveRule"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum\/keepactiverule","type":"topic","role":"symbol","kind":"symbol","title":"NavigationOption.keepActiveRule"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum":{"navigatorTitle":[{"text":"SDKLanguageOption","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKLanguageOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","kind":"symbol","title":"SDKLanguageOption","abstract":[{"type":"text","text":"Option to specify the language to use for the targeting."}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationChannel","kind":"identifier"}],"abstract":[],"title":"ConversationChannel","type":"topic","navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum/clearActiveRule":{"role":"symbol","title":"NavigationOption.clearActiveRule","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearActiveRule"}],"abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/clearActiveRule","url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum\/clearactiverule","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationOption"}],"abstract":[],"navigatorTitle":[{"text":"NavigationOption","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","title":"NavigationOption","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingrule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","title":"TargetingRule","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TargetingRule","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum/activateNewRule(targetingRule:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum\/activateNewRule(targetingRule:)","title":"NavigationOption.activateNewRule(targetingRule:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"activateNewRule","kind":"identifier"},{"kind":"text","text":"("},{"text":"targetingRule","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TargetingRule","preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum\/activatenewrule(targetingrule:)","type":"topic","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language":{"abstract":[{"text":"ISO639-1 language.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Language","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/language","kind":"symbol","title":"Language","navigatorTitle":[{"kind":"identifier","text":"Language"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","role":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"title":"TargetingError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TargetingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","url":"\/documentation\/iadvizeconversationsdk\/targetingerror","abstract":[{"type":"codeVoice","code":"TargetingError"},{"type":"text","text":" is an error that can occur when you try to activate a targeting rule using"},{"type":"text","text":" "},{"code":"TargetingController.activateTargetingRule(targetingRule:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"TargetingController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","value":[{"kind":"identifier","text":"TargetingController"}],"op":"replace"},{"op":"replace","value":[{"text":"TargetingController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/title","op":"replace","value":"TargetingControllerDelegate"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/fragments","value":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/navigatorTitle"},{"value":"TargetingRule","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","op":"replace"},{"value":[{"text":"TargetingRule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments"},{"value":[{"kind":"identifier","text":"TargetingRule"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle"},{"op":"replace","value":"TargetingError","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title"},{"value":[{"kind":"identifier","text":"TargetingError"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle","op":"replace","value":[{"text":"TargetingError","kind":"identifier"}]}]}]}