{"abstract":[{"type":"text","text":"An object that allows to configure push notifications."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)NotificationController","title":"NotificationController","navigatorTitle":[{"text":"NotificationController","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"}],"symbolKind":"class","roleHeading":"Class","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"],"type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode"],"title":"Push Notifications","anchor":"Push-Notifications"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationController"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/clearIAdvizePushNotifications()","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/disablePushNotifications(completion:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/enablePushNotifications(completion:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/isIAdvizePushNotification(with:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken(_:applicationMode:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/notificationcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/notificationcontroller"]}],"references":{"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/registerPushToken:applicationMode:":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken:applicationMode:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerPushToken:applicationMode:"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/registerpushtoken:applicationmode:","type":"topic","title":"registerPushToken:applicationMode:","role":"symbol","navigatorTitle":[{"text":"registerPushToken:applicationMode:","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/disablePushNotifications(completion:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/disablePushNotifications(completion:)","abstract":[{"type":"text","text":"Disable push notifications for the current visitor on this device."}],"type":"topic","title":"disablePushNotifications(completion:)","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/disablepushnotifications(completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disablePushNotifications"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"disablePushNotificationsWithCompletion:","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/isIAdvizePushNotification(with:)":{"navigatorTitle":[{"kind":"identifier","text":"isIAdvizePushNotificationWith:"}],"title":"isIAdvizePushNotification(with:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Indicates if a received push notification is related to the iAdvize SDK."}],"url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/isiadvizepushnotification(with:)","type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/isIAdvizePushNotification(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isIAdvizePushNotification","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/enablePushNotifications(completion:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/enablePushNotifications(completion:)","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/enablepushnotifications(completion:)","title":"enablePushNotifications(completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enablePushNotifications"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"abstract":[{"text":"Enable push notifications for the current visitor on this device.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"enablePushNotificationsWithCompletion:"}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ApplicationMode":{"navigatorTitle":[{"text":"ApplicationMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Mode for APNS."}],"title":"ApplicationMode","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ApplicationMode","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApplicationMode"}],"url":"\/documentation\/iadvizeconversationsdk\/applicationmode"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController","navigatorTitle":[{"kind":"identifier","text":"NotificationController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller","title":"NotificationController","role":"symbol","abstract":[{"type":"text","text":"An object that allows to configure push notifications."}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/init":{"role":"symbol","abstract":[],"title":"init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/init","type":"topic"},"doc://com.iadvize.conversation.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/registerPushToken(_:applicationMode:)":{"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken(_:applicationMode:)","abstract":[{"text":"Register the push token of your visitor device so it will receive push notifications for new messages received","type":"text"},{"type":"text","text":" "},{"text":"during the conversation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerPushToken","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"applicationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK15ApplicationModeO","text":"ApplicationMode"},{"text":")","kind":"text"}],"url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/registerpushtoken(_:applicationmode:)","kind":"symbol","type":"topic","title":"registerPushToken(_:applicationMode:)"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NotificationController/clearIAdvizePushNotifications()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearIAdvizePushNotifications","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/clearIAdvizePushNotifications()","url":"\/documentation\/iadvizeconversationsdk\/notificationcontroller\/cleariadvizepushnotifications()","role":"symbol","navigatorTitle":[{"text":"clearIAdvizePushNotifications","kind":"identifier"}],"title":"clearIAdvizePushNotifications()","abstract":[{"type":"text","text":"Clears the iAdvize SDK push notifications from the Notification Center."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"NotificationController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"NotificationController"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"NotificationController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/clearIAdvizePushNotifications()","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/disablePushNotifications(completion:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/enablePushNotifications(completion:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/init","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/isIAdvizePushNotification(with:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NotificationController\/registerPushToken:applicationMode:"],"generated":true}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationController"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"disablePushNotificationsWithCompletion:","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1disablePushNotifications(completion:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"disablePushNotificationsWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1disablePushNotifications(completion:)\/fragments"},{"value":"isIAdvizePushNotificationWith:","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1isIAdvizePushNotification(with:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isIAdvizePushNotificationWith:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1isIAdvizePushNotification(with:)\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1enablePushNotifications(completion:)\/title","value":"enablePushNotificationsWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1enablePushNotifications(completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"enablePushNotificationsWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/title","value":"NotificationController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/fragments","op":"replace","value":[{"kind":"identifier","text":"NotificationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController\/navigatorTitle","value":[{"kind":"identifier","text":"NotificationController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1clearIAdvizePushNotifications()\/title","value":"clearIAdvizePushNotifications"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1NotificationController~1clearIAdvizePushNotifications()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearIAdvizePushNotifications"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}