{"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKLanguageOption"}],"title":"SDKLanguageOption","externalID":"s:22IAdvizeConversationSDK17SDKLanguageOptionO","role":"symbol","modules":[{"name":"IAdvizeConversationSDK"}],"navigatorTitle":[{"text":"SDKLanguageOption","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKLanguageOption"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum"]}],"sections":[],"seeAlsoSections":[{"title":"Targeting","anchor":"Targeting","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum"],"generated":true}],"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","interfaceLanguage":"swift"},"abstract":[{"text":"Option to specify the language to use for the targeting.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum\/custom(value:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum\/default"],"anchor":"Enumeration-Cases","generated":true}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingController"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingController"}],"title":"TargetingController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"kind":"symbol","role":"symbol","title":"ConversationChannel","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationChannel"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum/default":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum\/default","title":"SDKLanguageOption.default","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum\/default","abstract":[{"text":"Use the device language.","type":"text"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingrule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"abstract":[],"navigatorTitle":[{"text":"NavigationOption","kind":"identifier"}],"title":"NavigationOption","url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","type":"topic","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NavigationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum/custom(value:)":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"custom","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:22IAdvizeConversationSDK8LanguageO","text":"Language"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Use the specified language."}],"role":"symbol","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum\/custom(value:)","title":"SDKLanguageOption.custom(value:)","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum\/custom(value:)","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","url":"\/documentation\/iadvizeconversationsdk\/language","title":"Language","role":"symbol","navigatorTitle":[{"text":"Language","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"ISO639-1 language."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Language","kind":"identifier"}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"abstract":[{"code":"TargetingError","type":"codeVoice"},{"text":" is an error that can occur when you try to activate a targeting rule using","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"TargetingController.activateTargetingRule(targetingRule:)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingError"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingerror","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"title":"TargetingError","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKLanguageOption"}],"navigatorTitle":[{"kind":"identifier","text":"SDKLanguageOption"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum","title":"SDKLanguageOption","kind":"symbol","abstract":[{"type":"text","text":"Option to specify the language to use for the targeting."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","title":"TargetingControllerDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingControllerDelegate"}],"abstract":[{"type":"text","text":"An object that is notified about the targeting process."}],"navigatorTitle":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"TargetingController","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title"},{"value":[{"text":"TargetingController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","value":[{"text":"TargetingController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","value":"TargetingRule"},{"value":[{"text":"TargetingRule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","op":"replace"},{"value":[{"text":"TargetingRule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","op":"replace"},{"value":"TargetingError","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments","op":"replace","value":[{"text":"TargetingError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle","op":"replace","value":[{"text":"TargetingError","kind":"identifier"}]},{"value":"TargetingControllerDelegate","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/fragments","value":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/navigatorTitle"}]}]}