{"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingControllerDelegate"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"title":"TargetingControllerDelegate","navigatorTitle":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(pl)TargetingControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"TargetingControllerDelegate","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"title":"Targeting","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum"],"anchor":"Targeting","generated":true}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate\/activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate\/activeTargetingRuleDidFailToUpdate(error:)"],"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate"]}],"sections":[],"abstract":[{"text":"An object that is notified about the targeting process.","type":"text"}],"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKLanguageOption"}],"navigatorTitle":[{"kind":"identifier","text":"SDKLanguageOption"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum","title":"SDKLanguageOption","kind":"symbol","abstract":[{"type":"text","text":"Option to specify the language to use for the targeting."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingController"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingController"}],"title":"TargetingController","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"abstract":[],"navigatorTitle":[{"text":"NavigationOption","kind":"identifier"}],"title":"NavigationOption","url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","type":"topic","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"NavigationOption","kind":"identifier"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate/activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)":{"title":"activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)","kind":"symbol","abstract":[{"text":"Called when the availability of the active targeting rule changed.","type":"text"}],"required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"activeTargetingRuleAvailabilityDidUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isActiveTargetingRuleAvailable","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate\/activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)","url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate\/activetargetingruleavailabilitydidupdate(isactivetargetingruleavailable:)","navigatorTitle":[{"kind":"identifier","text":"activeTargetingRuleAvailabilityDidUpdateWithIsActiveTargetingRuleAvailable:"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","url":"\/documentation\/iadvizeconversationsdk\/language","title":"Language","role":"symbol","navigatorTitle":[{"text":"Language","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"ISO639-1 language."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Language","kind":"identifier"}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"kind":"symbol","role":"symbol","title":"ConversationChannel","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationChannel"}],"abstract":[],"url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","abstract":[{"text":"Take your app to the next level and provide a ","type":"text"},{"inlineContent":[{"type":"text","text":"unique conversational experience"}],"type":"strong"},{"type":"text","text":" to your users!"}],"url":"\/documentation\/iadvizeconversationsdk","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","title":"TargetingControllerDelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingControllerDelegate"}],"abstract":[{"type":"text","text":"An object that is notified about the targeting process."}],"navigatorTitle":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate/activeTargetingRuleDidFailToUpdate(error:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate\/activeTargetingRuleDidFailToUpdate(error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activeTargetingRuleDidFailToUpdate"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TargetingError","kind":"typeIdentifier","preciseIdentifier":"c:@M@IAdvizeConversationSDK@E@TargetingError"},{"kind":"text","text":")"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate\/activetargetingruledidfailtoupdate(error:)","navigatorTitle":[{"text":"activeTargetingRuleDidFailToUpdateWithError:","kind":"identifier"}],"kind":"symbol","required":true,"title":"activeTargetingRuleDidFailToUpdate(error:)","type":"topic","role":"symbol","abstract":[{"text":"Called when the SDK failed to activate a targeting rule.","type":"text"}]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"abstract":[{"code":"TargetingError","type":"codeVoice"},{"text":" is an error that can occur when you try to activate a targeting rule using","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"TargetingController.activateTargetingRule(targetingRule:)"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingError"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingerror","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"title":"TargetingError","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","kind":"symbol","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TargetingRule"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingrule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"title":"TargetingRule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TargetingControllerDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate\/activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate\/activeTargetingRuleDidFailToUpdate(error:)"],"anchor":"Instance-Methods"}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError"],"anchor":"Targeting","title":"Targeting","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TargetingControllerDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title","value":"TargetingController"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments","value":[{"kind":"identifier","text":"TargetingController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","value":[{"text":"TargetingController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate~1activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)\/title","value":"activeTargetingRuleAvailabilityDidUpdateWithIsActiveTargetingRuleAvailable:"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate~1activeTargetingRuleAvailabilityDidUpdate(isActiveTargetingRuleAvailable:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"activeTargetingRuleAvailabilityDidUpdateWithIsActiveTargetingRuleAvailable:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/title","op":"replace","value":"TargetingControllerDelegate"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/fragments","op":"replace","value":[{"text":"TargetingControllerDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate~1activeTargetingRuleDidFailToUpdate(error:)\/title","op":"replace","value":"activeTargetingRuleDidFailToUpdateWithError:"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate~1activeTargetingRuleDidFailToUpdate(error:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"activeTargetingRuleDidFailToUpdateWithError:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"TargetingError","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title"},{"value":[{"text":"TargetingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle","value":[{"text":"TargetingError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","value":"TargetingRule","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","op":"replace","value":[{"kind":"identifier","text":"TargetingRule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","value":[{"kind":"identifier","text":"TargetingRule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}