{"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/init(id:conversationChannel:)"],"generated":true,"anchor":"Initializers"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SE","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"],"type":"conformsTo","kind":"relationships"}],"metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)TargetingRule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TargetingRule"}],"symbolKind":"class","role":"symbol","title":"TargetingRule","navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"generated":true,"anchor":"Targeting","title":"Targeting","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TargetingRule","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingrule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/targetingrule"]}],"references":{"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingError":{"title":"TargetingError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TargetingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TargetingError"}],"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError","url":"\/documentation\/iadvizeconversationsdk\/targetingerror","abstract":[{"type":"codeVoice","code":"TargetingError"},{"type":"text","text":" is an error that can occur when you try to activate a targeting rule using"},{"type":"text","text":" "},{"code":"TargetingController.activateTargetingRule(targetingRule:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule/init(id:conversationChannel:)":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/init(id:conversationChannel:)","url":"\/documentation\/iadvizeconversationsdk\/targetingrule\/init(id:conversationchannel:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"text":", ","kind":"text"},{"text":"conversationChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:22IAdvizeConversationSDK0B7ChannelO","kind":"typeIdentifier","text":"ConversationChannel"},{"kind":"text","text":")"}],"title":"init(id:conversationChannel:)","role":"symbol","abstract":[]},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/NavigationOption-swift.enum":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NavigationOption"}],"abstract":[],"navigatorTitle":[{"text":"NavigationOption","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/navigationoption-swift.enum","role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/NavigationOption-swift.enum","title":"NavigationOption","kind":"symbol"},"doc://com.iadvize.conversation.sdk/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s8CopyableP"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TargetingController","kind":"identifier"}],"navigatorTitle":[{"text":"TargetingController","kind":"identifier"}],"title":"TargetingController","abstract":[{"type":"text","text":"An object that controls the targeting process, i.e. the workflow leading to the display or not of the chat button."}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","type":"topic","kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/targetingcontroller","role":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"inlineContent":[{"text":"unique conversational experience","type":"text"}],"type":"strong"},{"text":" to your users!","type":"text"}],"url":"\/documentation\/iadvizeconversationsdk","kind":"symbol","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","role":"collection","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/SDKLanguageOption-swift.enum":{"navigatorTitle":[{"text":"SDKLanguageOption","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKLanguageOption"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/SDKLanguageOption-swift.enum","kind":"symbol","title":"SDKLanguageOption","abstract":[{"type":"text","text":"Option to specify the language to use for the targeting."}],"role":"symbol","url":"\/documentation\/iadvizeconversationsdk\/sdklanguageoption-swift.enum","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/ConversationChannel-swift.enum":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationChannel","kind":"identifier"}],"abstract":[],"title":"ConversationChannel","type":"topic","navigatorTitle":[{"text":"ConversationChannel","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/iadvizeconversationsdk\/conversationchannel-swift.enum","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/ConversationChannel-swift.enum"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule":{"navigatorTitle":[{"kind":"identifier","text":"TargetingRule"}],"url":"\/documentation\/iadvizeconversationsdk\/targetingrule","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule","type":"topic","title":"TargetingRule","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TargetingRule","kind":"identifier"}],"role":"symbol"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP"},"doc://com.iadvize.conversation.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingRule/initWithId:objcConversationChannel:":{"role":"symbol","kind":"symbol","title":"initWithId:objcConversationChannel:","url":"\/documentation\/iadvizeconversationsdk\/targetingrule\/initwithid:objcconversationchannel:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:objcConversationChannel:"}],"navigatorTitle":[{"text":"initWithId:objcConversationChannel:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/initWithId:objcConversationChannel:","type":"topic"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TargetingControllerDelegate":{"kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","role":"symbol","abstract":[{"text":"An object that is notified about the targeting process.","type":"text"}],"title":"TargetingControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TargetingControllerDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/targetingcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"TargetingControllerDelegate"}]},"doc://com.iadvize.conversation.sdk/SE":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/SE","title":"Swift.Encodable","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Language":{"abstract":[{"text":"ISO639-1 language.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Language","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/language","kind":"symbol","title":"Language","navigatorTitle":[{"kind":"identifier","text":"Language"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Language","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"TargetingRule","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"TargetingRule"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"TargetingRule","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingRule\/initWithId:objcConversationChannel:"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingController","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingControllerDelegate","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TargetingError"],"anchor":"Targeting","title":"Targeting","generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TargetingRule","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"TargetingError","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/title"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/fragments","value":[{"text":"TargetingError","kind":"identifier"}],"op":"replace"},{"value":[{"text":"TargetingError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingError\/navigatorTitle"},{"value":"TargetingController","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/title"},{"value":[{"kind":"identifier","text":"TargetingController"}],"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/fragments"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TargetingController"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/title","value":"TargetingRule","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/fragments","op":"replace","value":[{"kind":"identifier","text":"TargetingRule"}]},{"value":[{"kind":"identifier","text":"TargetingRule"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingRule\/navigatorTitle","op":"replace"},{"value":"TargetingControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"TargetingControllerDelegate"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TargetingControllerDelegate\/navigatorTitle","value":[{"text":"TargetingControllerDelegate","kind":"identifier"}],"op":"replace"}]}]}