{"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/registerTransaction(_:)"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"]}],"seeAlsoSections":[{"title":"Transactions","anchor":"Transactions","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransactionController"}]}]}],"metadata":{"role":"symbol","title":"TransactionController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransactionController","kind":"identifier"}],"modules":[{"name":"IAdvizeConversationSDK"}],"externalID":"c:@M@IAdvizeConversationSDK@objc(cs)TransactionController","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"TransactionController","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iadvizeconversationsdk\/transactioncontroller"]},{"paths":["\/documentation\/iadvizeconversationsdk\/transactioncontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Currency":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Currency"}],"navigatorTitle":[{"kind":"identifier","text":"Currency"}],"abstract":[{"type":"text","text":"Currency used in a "},{"type":"codeVoice","code":"Transaction"},{"type":"text","text":"."}],"title":"Currency","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Currency","url":"\/documentation\/iadvizeconversationsdk\/currency","type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController":{"abstract":[{"type":"text","text":"An object that allows to register transactions."}],"title":"TransactionController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransactionController"}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TransactionController","kind":"identifier"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject"},"doc://com.iadvize.conversation.sdk/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP"},"doc://com.iadvize.conversation.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController/registerTransaction(_:)":{"abstract":[{"text":"Register a new transaction concluded by your visitor.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/registerTransaction(_:)","navigatorTitle":[{"kind":"identifier","text":"registerTransaction:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerTransaction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@IAdvizeConversationSDK@objc(cs)Transaction","text":"Transaction","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller\/registertransaction(_:)","kind":"symbol","type":"topic","title":"registerTransaction(_:)"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"},"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/TransactionController/init":{"abstract":[],"kind":"symbol","role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/iadvizeconversationsdk\/transactioncontroller\/init","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/Transaction":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Transaction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Transaction"}],"url":"\/documentation\/iadvizeconversationsdk\/transaction","abstract":[{"text":"Describes a visitor transaction.","type":"text"}],"title":"Transaction","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TransactionController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"TransactionController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"TransactionController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/init","doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/TransactionController\/registerTransaction(_:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Transactions","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/Transaction"],"title":"Transactions"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"TransactionController","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/title","op":"replace","value":"TransactionController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/fragments","value":[{"kind":"identifier","text":"TransactionController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController\/navigatorTitle","value":[{"text":"TransactionController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController~1registerTransaction(_:)\/title","value":"registerTransaction:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1TransactionController~1registerTransaction(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerTransaction:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/title","value":"Transaction"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/fragments","op":"replace","value":[{"text":"Transaction","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"Transaction"}],"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1Transaction\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}