{"seeAlsoSections":[{"anchor":"Visitor","title":"Visitor","generated":true,"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData"]}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/registerCustomData(customData:completion:)"],"title":"Instance Methods"}],"metadata":{"modules":[{"name":"IAdvizeConversationSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisitorController"}],"title":"VisitorController","externalID":"c:@M@IAdvizeConversationSDK@objc(cs)VisitorController","navigatorTitle":[{"kind":"identifier","text":"VisitorController"}],"roleHeading":"Class","symbolKind":"class"},"identifier":{"url":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","doc:\/\/com.iadvize.conversation.sdk\/SQ","doc:\/\/com.iadvize.conversation.sdk\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VisitorController"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/iadvizeconversationsdk\/visitorcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/iadvizeconversationsdk\/visitorcontroller"]}],"sections":[],"references":{"doc://com.iadvize.conversation.sdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SQ"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController/init":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/init","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller\/init","title":"init"},"doc://com.iadvize.conversation.sdk/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s7CVarArgP","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/CustomData":{"title":"CustomData","abstract":[],"role":"symbol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/CustomData","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomData","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CustomData"}],"url":"\/documentation\/iadvizeconversationsdk\/customdata","kind":"symbol","type":"topic"},"doc://com.iadvize.conversation.sdk/SH":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/SH","title":"Swift.Hashable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK":{"type":"topic","abstract":[{"type":"text","text":"Take your app to the next level and provide a "},{"type":"strong","inlineContent":[{"type":"text","text":"unique conversational experience"}]},{"type":"text","text":" to your users!"}],"role":"collection","url":"\/documentation\/iadvizeconversationsdk","title":"IAdvizeConversationSDK","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK","kind":"symbol"},"doc://com.iadvize.conversation.sdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject","title":"NSObject"},"doc://com.iadvize.conversation.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.iadvize.conversation.sdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.iadvize.conversation.sdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.iadvize.conversation.sdk\/objc(pl)NSObject","type":"unresolvable"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController/registerCustomData(customData:completion:)":{"abstract":[{"text":"Send a list of Visitor Custom Data.","type":"text"}],"identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/registerCustomData(customData:completion:)","type":"topic","url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller\/registercustomdata(customdata:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerCustomData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customData"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"CustomData","preciseIdentifier":"s:22IAdvizeConversationSDK10CustomDataO"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"title":"registerCustomData(customData:completion:)","role":"symbol","kind":"symbol"},"doc://com.iadvize.conversation.sdk/documentation/IAdvizeConversationSDK/VisitorController":{"type":"topic","identifier":"doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"VisitorController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitorController","kind":"identifier"}],"url":"\/documentation\/iadvizeconversationsdk\/visitorcontroller","role":"symbol","kind":"symbol","title":"VisitorController"},"doc://com.iadvize.conversation.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.iadvize.conversation.sdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"VisitorController","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"VisitorController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"VisitorController"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.iadvize.conversation.sdk\/documentation\/IAdvizeConversationSDK\/VisitorController\/init"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.iadvize.conversation.sdk\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"op":"replace","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"VisitorController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/title","value":"VisitorController"},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/fragments","op":"replace","value":[{"kind":"identifier","text":"VisitorController"}]},{"path":"\/references\/doc:~1~1com.iadvize.conversation.sdk~1documentation~1IAdvizeConversationSDK~1VisitorController\/navigatorTitle","value":[{"kind":"identifier","text":"VisitorController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}